### ISSUE TITLE
Ecosystem review of existing Cookie Analysis Tools 

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#14]
## Task

**Description:** 
Do a review of what is available out there in terms of tools for cookie analysis and classification, and deliver a summary of the state of the art and capabilities that should be accounted for in this tool.

This review shall be made with the target audience of the tool in mind, pin pointing existing tools and gaps applicable to relevant 3PCD user journeys.

**Steps to Complete:**
- [x] Compile list of available tooling options
- [ ] Analysis report with findings and recommendations

**Check:**
- [Best Free Cookie Checker for Websites](https://www.cookielawinfo.com/free-cookie-checker-for-websites/)
- [How to conduct a Cookie Audit](https://www.cookieyes.com/blog/how-cookies-work-and-how-to-do-cookie-audit/)
- [Ghostery](https://www.ghostery.com/)
- [Cookiebot](https://www.cookiebot.com/) 
- [Piwik PRO](https://piwik.pro/cookie-scanner/)
- [Cookieserve](https://www.cookieserve.com/)
- [Edit Cookies](https://chromewebstore.google.com/detail/fngmhnnpilhplaeedifhccceomclgfbg)
- [Cookie Audits](https://datatrue.com/en/guide-to-cookie-audit/)
- [Cookie Scanner](https://cookie-script.com/cookie-scanner)

**Comment by amedina** [comment]
@rahul286 FYI as discussed.

**Comment by pradeep910** [comment]
There are many chrome extensions available to edit, delete, list, import and export cookies. The list of cookies are editable within the same table.

Here are some examples: 

1. [Cookie Manager](https://chrome.google.com/webstore/detail/cookiemanager-cookie-edit/hdhngoamekjhmnpenphenpaiindoinpo) | [Github](https://github.com/joue-quroi/cookie-editor/)
2. [Edit This Cookie](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg) | [Github](https://github.com/ETCExtensions/Edit-This-Cookie/)
4. [Cookie Editor](https://chrome.google.com/webstore/detail/cookie-editor/hlkenndednhfkekhgcdicdfddnkalmdm/related?gclid=CjwKCAjw-b-kBhB-EiwA4fvKrD4fz9r1xIeo3flDTddZrLAyO1wxrRhFUmnj8VHYRJiV9_7fEuJE8RoCuasQAvD_BwE) | [Github](https://github.com/Moustachauve/cookie-editor)

**Comment by amedina** [comment]
@pradeep910 @maitreyie-chavan The outcome of this issue is the summary report we discussed. How is the progress on that?

**Comment by amedina** [comment]
Some of the capabilities we have identified so far include:

1. **Cookie Functional Classification**: Identify and categorize cookies according to their purpose: 'Essential', 'Performance', 'Analytics', 'Advertising', 'Third Party', etc.
2.  **Cookie "origin" classification**: 1P vs. 3P, which 3P providers. 
3. **Cookie Lifespan**: Provide information about the lifespan of each cookie — when does it expire, or is it a session cookie that expires when the browser is closed?
4. **Consent Management**: Determine which cookies are set before obtaining user consent, and which cookies are set afterwards.
5. **Domain Relationships**: visualize the relationships between a given site/domain and third-party domains using cookies?
6. **Alerts**:  for when new cookies are stored in the browser, or when existing cookies change their behavior or properties.

**Comment by maitreyie-chavan** [comment]
@amedina It's coming along well. We'll have more findings to discuss with you by ~next week.

**Comment by amedina** [comment]
Another source to assess: https://cookiepedia.co.uk/

**Comment by pradeep910** [comment]
We've analyzed following cookie analysis tools. While certain tools have distinctive features, others share common features. You can check this report/PDF file for better view along with screenshots. 
[Ecosystem review of existing Cookie Analysis Tools.pdf](https://github.com/GoogleChromeLabs/ps-analysis-tool/files/11959017/Ecosystem.review.of.existing.Cookie.Analysis.Tools.pdf)

### Analysis of Existing Cookie Tools

Cookie Tools or Extensions | Details
-- | --
[Cookie Editor](https://chrome.google.com/webstore/detail/cookie-editor/hlkenndednhfkekhgcdicdfddnkalmdm?hl=en) ([Github](https://github.com/joue-quroi/cookie-editor/)) | Shows list of cookies by domains and also allows to enable following attributes on cookie, along with updates to other cookie details of same site: Host OnlySessionSecureHTTP OnlyDoesn’t show 3P cookies.
[Edit This Cookie](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg) ([Github](https://github.com/ETCExtensions/Edit-This-Cookie/)) | Shows a settings page which opens in a new tab like this:It shows the table of cookies the same as DevTools.This extension lists 1P cookies by default. Doesn’t show 3P cookies.
[Ghostery](https://www.ghostery.com/) ([Github](https://github.com/ghostery/ghostery-extension)) | Extension Popup with simple view.Extension popup with detailed view Additionally provides following features:Cookie scanningTrack & AdblockerDetailed analytics of the trackers on a site.
[Privacy Badger](https://privacybadger.org/) & [Cover Your Tracks](https://coveryourtracks.eff.org/) by EFF.org | PrivacyBagder: Browser extension that automatically learns to block invisible trackers.Cover Your Tracks (formerly Panopticlick)Test your browser to see how well you are protected from tracking and fingerprinting
[Cookieyes](https://www.cookieyes.com/) & [CookieScript](https://cookie-script.com/) | Consent Management (a WordPress plugin available as well for cookie consent)Cookie policy and privacy policy generatorCookie Auto-Blocking: Automatically scan and block third-party scripts (such as Google Analytics, and Facebook Pixel) until the user consents.
[CookieSearch](https://cookiesearch.org/) | An extensive open-source database of cookies. It can be used to categorize the cookies into predefined categories such as Necessary, Analytics, Advertisement, Functional, Performance, and Others.
[CookieDatabase](https://cookiedatabase.org/)	 | Provide detailed information about cookies, Local Storage, pixels, and other tracking technologies.
[CookiePro](https://www.cookiepro.com/) | Scan websites for third-party trackers and collect cookie consent with branded cookie banners. Manage consent and scan apps to understand how your apps are sharing data.Cookie compliance monitoring (GDPR, CCPA, and LGPD)
[Awesome Cookie Manager](https://github.com/Phatsuo/awesome-cookie-manager) | This has a simple listing of all cookies in an icon popup, regardless of the tab you have open. To filter the list you can type in the domain name in the text field. However this is not able to give a list of cookies per tab, so it will not display any 3P cookies for a single tab.
[CookieServe](https://www.cookieserve.com/) | Provides a report of the cookies being used on the site with classification.
[SiteChecker](https://sitechecker.pro/cookie-checker/) | It’s a complete site audit tool, but it also highlights the cookies which can be manipulated via Javascript and whether the site has any defence mechanism or not.
[Iubenda](https://www.iubenda.com/en/scan#/wizard/site-url) | Displays the cookies compliance rate of a site. Example report - https://www.iubenda.com/en/flow/3217941/report#/compliance-report
[Swap My Cookies](https://chrome.google.com/webstore/detail/swap-my-cookies/dffhipnliikkblkhpjapbecpmoilcama) | Swap My Cookies manages your cookies, letting you log in on any website with several different accounts.It can help you create different profiles and each profile can have their individual cookies.
[Cookiepedia](https://cookiepedia.co.uk/) | Shows list of all cookies with purpose/classification.
[Am I Unique](https://amiunique.org/fingerprint) ([Extension](https://chrome.google.com/webstore/detail/amiunique/pigjfndpomdldkmoaiiigpbncemhjeca)) | Provide a complete analysis of browser fingerprinting properties.The browser extension can help to track the fingerprinting timelines.
[uBlockOrigin](https://ublockorigin.com/) | Has extension settings to enable/disable various levels or privacy (ads, tracking, malicious urls, etc.), Uses this database to find malicious URLs https://malware-filter.gitlab.io/urlhaus-filter/urlhaus-filter-online.txt, Uses this for EasyPrivacy checks https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/thirdparties/easyprivacy.txt. 
[CookieMetrix](https://www.cookiemetrix.com/) | Checks compliance with EU laws. Third-Party Session CookiesThird-Party Stored CookiesThird-Party Domains That Install CookiesExample report - https://www.cookiemetrix.com/display-report/indianexpress.com/16536dbfd6788b6983aad882d8d603ca

**Comment by pradeep910** [comment]
The analysis of cookie tools available in the ecosystem has been done, so closing this.
