### ISSUE TITLE
Deep Dive into Chrome DevTools Protocol (CDP) for Enhanced Extension Capabilities

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#156]
In order to maximize the capabilities of our Chrome extension, we need to have an in-depth understanding of the Chrome DevTools Protocol (CDP). This research task aims to comprehensively explore CDP and define strategies to best leverage its features for our extension's functionality. 

Outcome of this issue includes:

- [x] A detailed report on CDP's features and capabilities.
- [x] Potential ways to integrate CDP into our extension.
- [x] Recommendations on best practices and potential pitfalls.

References:
- [x] [Getting Started with CDP](https://github.com/aslushnikov/getting-started-with-cdp/blob/master/README.md)

**Comment by amedina** [comment]
Capture progress being made on migrating to CDP here. cc/ @sayedtaqui

**Comment by ayushnirwal** [comment]
Here is what I do in CLI if it may help.

- [requestWillBeSent](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestWillBeSent) and [requestWillBeSentExtraInfo](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestWillBeSentExtraInfo) for listening in to request sent from the browser. 

- [responseReceived](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-responseReceived) and [responseReceivedExtraInfo](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-responseReceivedExtraInfo) for listening in to responses.

- The network traffic is stored in maps then parsed to get cookie data.

The class [BrowserManagement class](https://github.com/GoogleChromeLabs/ps-analysis-tool/blob/44ff8129644ccc7fd1307917eda6681bdb6cfb46/packages/cli/src/utils/browserManagement/index.ts#L136) implements the procedures mentioned above.

**Comment by mohdsayed** [comment]
@amedina The research work of CDP is complete and shared with you for review.

**Comment by maitreyie-chavan** [comment]
Released as a part of [v0.4.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.0), closing this issue.

Related: https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/247
