### ISSUE TITLE
Issues with frame overlay

### ISSUE THREAD

**Issue by gagan0123** [GoogleChromeLabs/ps-analysis-tool#169]
**Describe the bug**
There are multiple sub issues, so keeping them separate here:

- [x] **Issue 1: Frame Overlay Persistence Across DevTools Tabs**

**Description:**

The frame overlay persists and remains visible across different tabs in Chrome DevTools when it should be confined only to the Privacy Sandbox Analysis Tool.

**Steps to Reproduce:**

1. Start the frame overlay by clicking on its icon in the extension.
2. Switch to another tab in Chrome DevTools (e.g., Network or Application).

**Expected Behavior:**

The frame overlay should only be visible when working in the Privacy Sandbox tab of the DevTools and should not persist when switching to other tabs.

---

- [x] **Issue 2: Frame Overlay Highlighting on Multiple Pages**

**Description:**

When navigating to a new tab after starting the frame overlay on a previous tab, the overlay in the first tab continues to highlight the frames.

**Steps to Reproduce:**

1. Start the frame overlay on one page.
2. Navigate to another page.
3. Use the frame overlay feature on the new page.
4. Go back to the old tab.

**Expected Behavior:**

When using the frame overlay feature on a new tab, any overlay from a previous tab should disappear, showing only the overlay for the current tab.

---

- [x] **Issue 3: Random Frame Overlay Misbehavior**

**Description:**

The frame overlay sometimes stops highlighting the hovered frame and its behavior becomes erratic, showing and disappearing randomly.

**Steps to Reproduce:**

1. Start the frame overlay on a tab.
2. Click on the overlay icon multiple times.
3. Hover over a frame.

**Expected Behavior:**

The frame overlay should consistently highlight the hovered frame without erratic behavior, regardless of the number of interactions.

---

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS
 - Browser: Google Chrome
 - Version: 117.0.5938.132

**Screencast**
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/Es0r_iqpKl0/0.jpg)](https://www.youtube.com/watch?v=Es0r_iqpKl0)

**Comment by sayedtaqui** [comment]
Thanks for reporting the issues, all of them have been fixed in https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/147

cc: @amedina

**Comment by sayedtaqui** [comment]
Closing as the fix was released with v0.3.0
