### ISSUE TITLE
CLI: Enable uploading analysis results 

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#203]
## Feature Request

**Description:**
Allow users to save the results of an analysis run, and to upload the results of a previous run. 

**Motivation:**
The CLI will be used to track evolution of sites regarding 3PCD issues. 

**User Story:**
As a developer or site owner, I want to be able to compare analysis results as I work on getting my side ready for 3PCD.

**Acceptance Criteria:**
- [ ] Upload analysis results from given folder
- [x] Decouple data generation from data rendering

**Comment by ayushnirwal** [comment]
@amedina @maitreyie-chavan PR #407 will address 2nd point in the acceptance criteria of this issue

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
