### ISSUE TITLE
CLI: Site analysis as a service

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#205]
## Feature Request

**Description:**
Implement PS site analysis service powered by PSAT's CLI. 

**Acceptance Criteria:**
- [ ] Service is available for public consumption
- [ ] Service performance is acceptable for a reasonable number of simultaneous users 
- [ ] Service is able to process both URLs and Sitemaps
- [ ] Service Architecture is well documented
- [ ] Suitable Domain is mapped to GCP project

**Comment by ayushnirwal** [comment]
> Service is able to process both URLs and Sitemaps

@mohdsayed In the case of sitemap analysis in CLI we allow user to test a subset of the sitemap through user input should that be replicated in the service too? 
cc: @amedina

**Comment by mohdsayed** [comment]
> > Service is able to process both URLs and Sitemaps
> 
> @mohdsayed In the case of sitemap analysis in CLI we allow user to test a subset of the sitemap through user input should that be replicated in the service too? cc: @amedina

Yes please!

**Comment by maitreyie-chavan** [comment]
Moving forward, our primary focus areas will be the PSAT Chrome extension and CLI. As a result, we will be closing this issue in favor of them.
