### ISSUE TITLE
Comprehensive tool documentation: PSAT, CLI How To, Site analysis

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#207]
## Feature Request

**Description:**
Provide comprehensive and effective tool documentation related to how to use PSAT's extension and CLI capabilities, as well as the application of both tools to the analysis of sites. 

**User Story:**
As a developer/user I want access to clear documentation enabling me to easily find the information I need to fully leverage the PSAT's capabilities. 

**Acceptance Criteria:**
- [x] PSAT and CLI's how tos
- [x] Site Analysis methodology
- [x] Warning on starting analyses on fresh Chrome instances to avoid issue with previously set cookies.
- [x] Special cases related to the debugging of cookie scenarios which may not be part of PSAT feature set (e.g. CORS)
- [x] One-click commands for setting evaluation environment

**Comment by amedina** [comment]
@gagan0123 Please provide details to be included in cases such as the CORS scenario.

**Comment by amedina** [comment]
@fellyph This is the issue encompassing PSAT How To.

**Comment by fellyph** [comment]
@amedina about the following items:  

1.`PSAT and CLI's how tos` we have [this section](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/A.-PSAT's-How-To#build-and-run-psats-cli) are you ok with it or do you want to update it?

3. ` Warning on starting analyses on fresh Chrome instances to avoid issues with previously set cookies.`

I can update the first paragraph at [Evaluation Evironment](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/B.-Evaluation-Environment)

```
To evaluate the impact of the Privacy Sandbox changes on Chrome, you now have two options for configuring your evaluation environment. They have a complete view of the impacts of cookie-related changes. 

You will need a brand-new Chrome instance with no extensions and no other cookies, so before starting tests, have an instance of Chrome free of extensions and without external cookies. 
- To clean the cookies from your browser, access: `chrome://settings/clearBrowserData`
- To disable the non-related extension for testing, access: `chrome://extensions/`

Creating a new Chrome profile for testing will help with this process. [Here at Chrome Documentation](https://support.google.com/chrome/answer/2364824?hl=en&co=GENIE.Platform%3DDesktop), you can get more information about it.
```

5. ` One-click commands for setting evaluation environment`

Is it [this solution](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/B.-Evaluation-Environment#method-1-using-custom-commands-simpler-method) with a terminal command accomplished the on-click solution:

**Comment by amedina** [comment]
@fellyph These sections are not at the level of quality needed. Currently the How To section just mentions the features, but there is no further guidance. Not the working in the issue title. 
'

> Is it [this solution](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/B.-Evaluation-Environment#method-1-using-custom-commands-simpler-method) with a terminal command accomplished the on-click solution:

It seems you did not complete writing this part. What do you mean?

**Comment by fellyph** [comment]
@amedina It was a question related to the CLI command solving the task related to a one-click solution.

**Comment by maitreyie-chavan** [comment]
Updates are now available in the Wiki, closing this issue.
