### ISSUE TITLE
Hide info card when collapsible header is clicked

### ISSUE THREAD

**Issue by mayan-000** [GoogleChromeLabs/ps-analysis-tool#209]
## Feature Request

**Description:**
Allow collapsing of only info card when clicked on landing page header dropdown. All the other components must stay consistently opened on whichever state of the header dropdown.

**User Story:**
As a user, I want to hide the info card that serves educational purposes about an API, but as the user becomes known of that API then he/she may prefer to keep it hidden and show only non-educational/functioning components.

**Comment by maitreyie-chavan** [comment]
Was addressed and released as a part of [v0.3.2](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.3.2)
