### ISSUE TITLE
CLI service returning empty results

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#215]
When running CLI service with <https://edition.cnn.com> as a paramter returns empty results (no cookies observed).

**Comment by ayushnirwal** [comment]
@amedina Would you sharing more details like what branch did you use? Have you used the `-nh` flag. Are you running the CLI in a special environment ( like a docker container ) ... etc.

For me it runs fine.


![Image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/53055971/bcb2ca43-de09-4b13-8b46-11d604a6db72)


If we don't have any environment differences then i will look into if UserAgent difference makes the output different.

**Comment by amedina** [comment]
I am in `main`. Still seeing empty results for this site: 

<img width="1796" alt="Screenshot 2023-10-31 at 10 45 55 AM" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/506089/8b6f3f29-cc90-4742-bb97-306aaf00cea2">

Also, I am seeing the "noisy" URL, which I thought had been fixed: 

`http://localhost:9000?path=.%2Fout%2Fedition-cnn.com%2Fout.js`

**Comment by ayushnirwal** [comment]
> Also, I am seeing the "noisy" URL, which I thought had been fixed:

Yes, It has been merged in with [this](https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/197)

Would you check if you have the recent commits merged into main?

**Comment by amedina** [comment]
Issue was on my setup. It is fixed.
