### ISSUE TITLE
Miscellaneous frame overlay issues

### ISSUE THREAD

**Issue by mohdsayed** [GoogleChromeLabs/ps-analysis-tool#219]
## Task

**Description:**
The fame overlay feature works fine on the [demo site](https://psanalysis.site/). However, it may have multiple issues on different websites that use iframes in different ways. Therefore, this task is to identify and list down these issues, and then fix as many as possible.

**Related Issues:**
- https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/61
- https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/169

**Comment by maitreyie-chavan** [comment]
Fixed and released as a part of [v0.4.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.0), closing this issue.
