### ISSUE TITLE
CLI: Analyze a set of sites (not in a sitemap)

### ISSUE THREAD

**Issue by mohdsayed** [GoogleChromeLabs/ps-analysis-tool#220]
## Feature Request

**Description:**
Provide ability for users to input a set of related websites for analyzing cookie usage among them. This is an additional use case augmenting the sitemap input option. 

**Acceptance Criteria:**
TDB

**Comment by ayushnirwal** [comment]
@mohdsayed Could you please clarify more how should the user input that data? I'm thinking they can pass a xml site file to the CLI tool.

cc: @amedina

**Comment by amedina** [comment]
The input format could be the same as a sitemap, but from a semantics perspective it would be clearer for users to specify something like a comma-separated list of URLs, or an input file with the list of domains to be analyzed.

**Comment by ayushnirwal** [comment]
This feature in implemented and merged in the `develop` branch and is ready for release.

**Comment by prasadnevase** [comment]
@ayushnirwal - this is great. I've updated the docs to mention this addition

https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/A.-PSAT's-How-To#build-and-run-psats-cli

**Comment by maitreyie-chavan** [comment]
Released as a part of [v0.4.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.0), closing this issue.
