### ISSUE TITLE
Cookie tables bogus updating

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#222]
**Describe the bug**
When navigating from an analyzed site to another, the current cookie table is updated with cookies from the new site, but the associated frames do not change. When the frames finally change, the tool transitions to the Cookies landing page violating the principle of maintaining the user flow consistent. 

**To Reproduce**
1. Go to `https://edition.ccn.com`
2. Observe the cookies table and corresponding table
3. Navigate to `https://aa.com`
4. See the cookie table being updated, the frames from the previous site remain 
5. The tool finally updates and jumps back to the landing page

**Expected behavior**
1. The cookies table should not be updated independently from the frames
2. The tool should not close the cookie table and jump to the Cookie landing page. The user is observing the table and that should remain, consistent with the principle of maintaining the user flow.

This should have been caught easily during developer testing, and definitely should have been caught during QA.

**Comment by mohdsayed** [comment]
Related issue https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/151
