### ISSUE TITLE
Ensure the text has better clarity for RWS instructions

### ISSUE THREAD

**Issue by gagan0123** [GoogleChromeLabs/ps-analysis-tool#224]
On the RWS page, once we generate the JSON resources, the following instructions need to be more precise:

**Step 1:**
From:
> Add the .well-known file to the primary domain with the following content:

To:
> Add the file `related-website-set.json` in the directory `.well-known` of the primary domain with the following content:

**Step 2:**
From:
> Add the .well-known file to all the other domains in your set with the following content:

To:
> Add the file `related-website-set.json` in the directory `.well-known` of all the other domains in your set with the following content:

**Screenshot**
![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/1535505/1fc7819b-ad0a-4122-8fde-d11c1d524f2c)

**Comment by mayan-000** [comment]
Merged to `main`.
