### ISSUE TITLE
Make the Refresh button more responsive

### ISSUE THREAD

**Issue by fellyph** [GoogleChromeLabs/ps-analysis-tool#226]
**Describe the bug**
At the table of cookies on top-level controls, the refresh button doesn't have a state for the click event. It is hard for the user to know whether the action was taken. 

**To Reproduce**
1. Go to DevTools
2. Click on the Privacy Sandbox tab
3. Open the Cookies section on the sidebar
4. Go to the table of cookies
5. Click on the refresh button on the top-level controls.

**Expected behavior**
The click action should give feedback to the user when the action is taken. Or if the button is disabled, just change the cursor.

**Screenshots**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/330792/73636c0f-912e-430e-b31b-4df810029ab3

**Desktop:**
 - OS: MacOS
 - Browser: Chrome
 - Version 119

**Comment by ayushnirwal** [comment]
Released in 0.3.2
