### ISSUE TITLE
Make the Search field cleaner

### ISSUE THREAD

**Issue by fellyph** [GoogleChromeLabs/ps-analysis-tool#227]
## Feature Request

**Description:**
The search field at the table of cookies has the clear field button always visible:
![Screenshot 2023-11-03 at 09 46 28](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/330792/8d36ee10-bab5-4542-ba67-dfaad1ffa637)

The feature suggestion is making similar behavior to the search filter at DevTools, where the clear button only appears when the field is filled and inside the search field:
![Screenshot 2023-11-03 at 09 46 53](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/330792/054b5226-9c25-4a19-bd3d-af10585f2e94)

**Motivation:**
Make the UI cleaner and follow the same standard as the Chrome DevTools

**User Story:**
As a user, I want to use similar search fields as DevTools so that I can have a consistent UI.

**Acceptance Criteria:**
- [ ] the clear button appears inside the field
- [ ] The button only appears when the users add content to the field
- [ ] Once the user cleans the field the clear button disappears

**Comment by mayan-000** [comment]
Chrome recently celebrated its 15th birthday, and with the update came the implementation of `Material You`. Prior to the update, the UI of the tool was consistent with Chrome dev tools.
We'll look into updating the UI to match the new design and ensure consistency with Chrome's UI.

**Comment by mayan-000** [comment]
This has been completed as of PR #243, merged to `develop`, and is ready for release.

**Comment by fellyph** [comment]
Good news @mayan-000

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.4.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.0), closing this issue.
