### ISSUE TITLE
Add option to print or export the report

### ISSUE THREAD

**Issue by fellyph** [GoogleChromeLabs/ps-analysis-tool#228]
## Feature Request

**Description:**
The CLI has an option to download CSV files, would be nice to have this option on the extension to export a CSV file and print a report, which the users can use to save the report in a PDF file.

![Screenshot 2023-11-03 at 17 12 59](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/330792/3883db33-3b88-4b9e-b16a-41492f451c71)

**Motivation:**
Save a CSV or a PDF version it is a great way to send the report via email or keep the history of the report to follow up or document the migration from third-party cookies.

**User Story:**
As a User, I want to print or export the cookies report so that I can share it.

**Acceptance Criteria:**
- [ ] add an option to export the report
- [ ] add an option to print the report

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.7](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.7.0)
