### ISSUE TITLE
Wiki: Add section on known Special cases

### ISSUE THREAD

**Issue by maitreyie-chavan** [GoogleChromeLabs/ps-analysis-tool#239]
## Task

**Description:**
Shed light on scenarios which are part of the debugging process of cookies, but they are not related to 3PCD and therefore may not have associated features on PSAT. For example, cookies set but not transferred on every request due to CORS configuration settings determined by servers. 

**Additional Information:**
Gagan and Saurabh to collaborate on the same and document known + new scenarios that get uncovered.

**Comment by actual-saurabh** [comment]
Are these or any references compiled somewhere. If not, could @gagan0123 compile a rough list of references that we could expand in the handbook.

**Comment by gagan0123** [comment]
@actual-saurabh 

Have already shared WIP FAQ Doc, and docs containing list of questions asked during the Roadshow. Please let me know if you need anything else to start on this.

**Comment by maitreyie-chavan** [comment]
Incorporated between Wiki and Support Qs.
