### ISSUE TITLE
Display partitioned attribute

### ISSUE THREAD

**Issue by maitreyie-chavan** [GoogleChromeLabs/ps-analysis-tool#242]
## Feature Request

**Description:**
Capture the partitioned attribute and add it to the Cookie table in PSAT panel.

**Comment by dmdabbs** [comment]
Yes, please. Sites will want to see where new CHIPS cookies are in use by partners on their site.

**Comment by maitreyie-chavan** [comment]
Released as a part of [v0.4.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.0), closing this issue.
