### ISSUE TITLE
Show"Cookie Accepted" column earlier in the cookie table

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#245]
The "Cookie Accepted" column in the cookie table conveys very important information in the process of debugging 3PCD issues. It would be good to move it to the left in the table so that the information is conveyed earlier to users without the need to scroll the table to the right.

**Comment by amovar18** [comment]
This column will be replaced by the PR for issue https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/252 under the epic of Chrome Devtools Protocol integration.
