### ISSUE TITLE
Add clear documentation regarding "Cookie Accepted" column

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#246]
PSAT provides the useful capability of showing cookies that have been blocked by the browser in the cookie table and indicating the blockage in the "Cookie Accepted" column. This feature will be improved further in upcoming versions of the tool.

The problem right now is that this feature is obscure to users, and they are getting confused because they are seeing cookies which are blocked appearing in PSAT but not on the Application/Cookies tab. This behavior needs to be made clear in the PSAT Wiki as soon as possible. 

@actual-saurabh @fellyph @gagan0123 @maitreyie-chavan

**Comment by actual-saurabh** [comment]
While we work on improving the overall documentation, as an interim measure, I suppose we could add a note under https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/A.-PSAT's-How-To#cookie-data-manipulation-and-analysis as follows:

> ### A note on Cookie Accepted
>
> Of all the cookies that the site attempts to set, some will be accepted by the browser and some would be rejected, in a 3PCD instance of Chrome (depending on whether they’re third-party or first-party cookies).
>
>The `Cookie Accepted` column of the _PSAT_ cookie table indicates this piece of information by adding a check icon (*✓*) next to the cookies that were accepted by the browser. Other cookies that don’t have this indicator, _have not been accepted by the browser_ and _are not set_.
>
>For this reason, such cookies won’t be displayed under `Applications > Cookies` in _Chrome Developer Tools_, since that displays the current state of the application and all the cookies that are actually set (accepted) and available for use.
>
>In contrast, `PSAT` is obviously interested in displaying cookies that are not set and not in use, for the purpose of analysis and repair.
>
>This is expected behavior, but sometimes is a source of confusion because of the apparent disparity between the information displayed under Application > Cookies and the PSAT extension.

Would this be sufficient at this time @amedina 

cc @gagan0123 @fellyph @maitreyie-chavan

**Comment by amedina** [comment]
@actual-saurabh That would be a good interim way to provide clarity on the semantics of the Cookie Accepted column. 

Given the feedback of the cluttering of that column, we should only mark the cookies that were not accepted with a cross mark. That would make the table easier to read.

Also, we the Cookie Accepted column should be presented "earlier" in the table (i.e. to the left), as the information conveyed is critical for debugging 3PCD scenarios.
