### ISSUE TITLE
Handle notification of Chrome DevTools debugger being attached to the Chrome window.

### ISSUE THREAD

**Issue by amovar18** [GoogleChromeLabs/ps-analysis-tool#248]
## Feature Request
Handle the notification shown during the usage of CDP.

**Description:**
Chrome shows a notification when a debugger is attached to a tab. The best way of handling this is to add a toggle button in the popup which will toggle the usage of CDP. This is being done to make sure that the extension doesn't consume more resources than required. Once switched on the CDP will be used along with the existing APIs. Once switched off only existing APIs will be used.

**Acceptance Criteria:**
- [x] A toggle button which will switch on and switch off the usage of CDP for extension.
- [x] Switching on should enable CDP and show the required information for cookies.
- [x] Switching off should disable CDP and stop capturing extra information.

**Comment by maitreyie-chavan** [comment]
Chrome DevTools Protocol (CDP) provides additional and critical information that will be very useful for analysis by the end-users. Having a world where is not used will not yield the same results, and hence this toggle will not be needed.
