### ISSUE TITLE
Use existing Chrome API in conjunction with Chrome DevTools Protocol.

### ISSUE THREAD

**Issue by amovar18** [GoogleChromeLabs/ps-analysis-tool#249]
## Feature Request

**Description:**
Ideally, CDP alone should be used for getting the data for the extension so that we can stop listening to network requests using `chrome.webRequest` but it was noticed that CDP doesn't give all the frames in the current site and there is no way to make cookie and frame association. So for the time being we have to use CDP along with the existing API.

**Acceptance Criteria:**
- [x] Associate cookie and frame from the chrome.webRequest.
- [x]  use CDP to get extra information regarding the cookie.

**Comment by maitreyie-chavan** [comment]
Released as a part of [v0.4.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.0), closing this issue.
