### ISSUE TITLE
Make use of Chrome DevTools Protocol to get extra information about cookies.

### ISSUE THREAD

**Issue by amovar18** [GoogleChromeLabs/ps-analysis-tool#250]
## Feature Request

**Description:**
Data regarding a cookie like `partitionKey`, `Priority`, `Size`, `BlockedReason` etc are not shown in the current usage. Using CDP with the current API will ensure we get more values for those cookies.

**Motivation:**
Implementing this we will get more details regarding the cookies that are being used in the current page.

**Acceptance Criteria:**
- [x] Cookies should show more values like  `partitionKey`, `Priority`, `Size`, `BlockedReason`  if they exist.
- [x] Add columns to display the same.

**Comment by maitreyie-chavan** [comment]
Released as a part of [v0.4.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.0), closing this issue.
