### ISSUE TITLE
Mapping Cookie Issue to their description.

### ISSUE THREAD

**Issue by amovar18** [GoogleChromeLabs/ps-analysis-tool#253]
## Feature Request

**Description:**
CDP provides cookies with issues, but the problem here is the issues are in the form of keys whose description is not provided so to provide the description to the user we need to map keys with their description from the official documentation.

**Motivation:**
A user will not be able to decipher what the issue is and why the cookie was blocked by reading the key. This helps in providing the description which can be then presented to the user.

**Acceptance Criteria:**
- [ ] A JSON file which consists of all the keys and their description.

**Comment by maitreyie-chavan** [comment]
Released as a part of [v0.4.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.0), closing this issue.
