### ISSUE TITLE
Refactoring: Move common utility functions of extension and CLI used for CDP.

### ISSUE THREAD

**Issue by amovar18** [GoogleChromeLabs/ps-analysis-tool#254]
## Feature Request

**Description:**
After moving to CDP there are chances that the functions are going to be the same for both CLI and extension. It will make sense to move these functions to a common package.

**Motivation:**
Moving common functions to a `common` package will provide a better developer experience.

**Acceptance Criteria:**
- [x] All the utility functions should reside in a common package
- [x] There should be no regression in the working of the tool.

**Comment by maitreyie-chavan** [comment]
Released as a part of [v0.4.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.0), closing this issue.
