### ISSUE TITLE
CLI/Service: Add capability to upload local sitemap file

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#256]
Currently the CLI and the Service allow a sitemap URL as input. Improve this capability by allowing users to upload a sitemap file from their computer.

**Comment by ayushnirwal** [comment]
As far as the CLI part of this issue, its interface will be updated to take sitemaps from the file system in PR #271. 
But for the sitemap support on the service the service has to be implemented which is tracked in the issue #205.

**Comment by maitreyie-chavan** [comment]
Released as a part of [v0.4.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.0), closing this issue.
