### ISSUE TITLE
CLI sitemap processing breaks

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#257]
**Describe the bug**
Running CLI tool on sitemap: https://gagan.pro/sitemaps/rakuten.xml, crashes ungracefully. 

**To Reproduce**
Run `npm run cli -- -s https://gagan.pro/sitemaps/rakuten.xml`

**Expected behavior**
Generated report for URLs in sitemap as well as aggregated report. 

**Screenshots**
<img width="1497" alt="Screenshot 2023-11-07 at 3 29 52 PM" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/506089/f185db0a-ecb2-482f-99c7-d58149fbc10b">

cc @gagan0123

**Comment by ayushnirwal** [comment]
@amedina @gagan0123 I was not able to recreate this bug on my end. Are there any changes in the sitemap which have fixed it?. 
By the looks of the error in the issue description, I think the 'destroy' method of the Wappalyzer class has been called early. So, PR #260 might also fix this.

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.4.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.0), closing this issue.
