### ISSUE TITLE
Make Cookie accepted column simpler by displayin only the negative case

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#259]
An important feature of PSAT is the listing of cookies that were blocked by the browser, and marking them as rejected (i.e. not accepted) in the "Cookie Accepted" column. We iterated on this column by first having only a check mark to express the non-blockage of a cookie, and no value to capture the blockage of a cookie. We then decided to express both the acceptance and rejection values in the Cookie Accepted column, as we found it was confusing for users to have no value for the rejected scenario. 

Now the opposite feedback was received: it is difficult to scan visually the column and determine which cookies have a check mark and which cookies have a cross. 

We want to iterate further and express only the negative case, that it, clearly express when a cookie was rejected (i.e. blocked) by the browser. This means that we can only add the cross mark for cookies that were blocked/rejected by the browser and leave the positive case (ie. cookie accepted) as black. This could be complemented by color highlighting of blocked cookies.

**Comment by mayan-000** [comment]
This has been moved under #247.

Assigning to @amovar18

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.4.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.0), closing this issue.

Related: https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/241
