### ISSUE TITLE
Enable Copy and Pasting from Cookie table via keyboard shortcuts

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#261]
As part of analyzing the information displayed in the Cookies table, there are scenarios where users need to copy content from the table and pasted in some other tooling they use during their analysis. Currently this is not possible and it should be enabled in a user-friendly way (e.g. via keyboard shortcuts).

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
