### ISSUE TITLE
"Download Report" for entire sitemap

### ISSUE THREAD

**Issue by gagan0123** [GoogleChromeLabs/ps-analysis-tool#262]
## Feature Request

**Description:**
In the CLI tool, when we run sitemap analysis, the "Download Report" button is only available for individual sites, but not for the entire sitemap. Can we please have a "Download Report" functionality for the entire sitemap so that we do not have to go to all individual sites?

**Motivation:**
When running the CLI tool on a sitemap with numerous URLs, the individual reports are not enough to do a comprehensive analysis. Instead, what is needed is an aggregated report, for the entire sitemap.

**Additional Functionality**
It would be a good to have a feature to be able to choose the fields we want to export, rather than fixed columns.

**Comment by kjnanda** [comment]
@mayan-000 For some sites it shows the folder name with `-` sign

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/455c89cd-d245-49a3-bc94-3f1495aefb4c)</kbd>

**Comment by mayan-000** [comment]
@kjnanda Can you provide the sitemap URL used?

**Comment by kjnanda** [comment]
@mayan-000 You can check any URL. Even with single site it shows folder name with `-` sign after the report is downloaded.

E.g. `npm run cli -- -u https://edition.cnn.com/ -nt -np`

**Comment by kjnanda** [comment]
@mayan-000 This looks good now.

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
