### ISSUE TITLE
Improve quality of CLI and Service Interfaces

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#263]
Currently the UI of the CLI and Service interfaces is clean and nice as a first version, but improvements should be made for placing the current "Download Report" functionality, as well as placing the upcoming features for uploading a previous analysis report (#203) and uploading a local sitemap file (#256).
The UI for the different pages where these functional capabilities will be added

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
