### ISSUE TITLE
[QA] Control cookies directly from Cookie Analysis extension

### ISSUE THREAD

**Issue by kjnanda** [GoogleChromeLabs/ps-analysis-tool#265]
Tested with below scenarios:

| **Test Case** | **Expected Result** | **Status** |
| --- | --- | --- |
| Hover effect for 'Clear Cookie' and 'Delete All Cookies' icons | Hover effect is applied to the icons. | ✅  |
| Deleting a cookie reflects in the Application Tab | Deletion in the table is reflected in the Application Tab. | ✅ |
| Delete All Cookies: Cookies removed from respective frame only | Cookies are removed only from the relevant frame. | ✅ |
| Delete All Cookies: Application Tab update | Cookies from the relevant frame in the Application Tab are erased. | ✅ |
| Delete All Cookies: Exclusion for cookies not listed under PSAT | Cookies not listed under PSAT are not erased from the Application Tab. | ✅ |
| Accessibility: Tab key | Tab key navigates through accessible elements. | ❎ https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/299 |
| Accessibility: Enter key | Enter key performs the expected action on the focused element. | ✅ |
| Accessibility: ESC key | ESC key performs the expected action | ✅ |
| Search + Delete functionality | Searching and deleting functions work seamlessly. | ✅ |
| Hover effect on delete icons relative to the active theme | Hover effect is applied to delete icons according to the active ✅ |
| Single delete cookie icon disabled by default | The single delete cookie icon is initially disabled. | ✅ |
| Empty frame: Disable single and bulk delete | Single and bulk delete icons are disabled for an empty frame. | ✅ |
| No errors thrown upon deleting cookies | Deleting cookies does not result in errors. | ✅ |
| Enable single delete icon after row selection | Single delete cookie icon becomes enabled after selecting a relevant row. | ✅ |
| Disable single and bulk delete after deleting all cookies in a frame | Icons are disabled after deleting all cookies in any selected frame. | ✅ |
| Disable single delete icon on selecting a blank row | Selecting a blank row disables the single delete cookie icon. | ✅ |
| No errors on clicking an empty row | Clicking on an empty row does not throw errors. | ✅ |
| Focus shift after deleting a cookie | Focus shifts to the next/previous row after deleting a cookie. | ✅ |
| Enable single delete icon for the current frame only | Single delete cookie icon is enabled only for the current frame. | ✅ |

---------

### UI/UX 🐞  - Clear All Cookies and Delete cookie

-----

- [x] **Improve the UX with Single cookie deletion in comparison to Application Tab**

| Expected Behavior | Actual Behavior |
|------ |----- |
| <li>The expected behavior for the clear single cookie icon is that it should become active only when the user selects a specific row.</li><li>Once a row is selected, subsequent clicks on the 'x' button should clear cookies sequentially</li> |<li>The current behavior of the clear single cookie icon does not align with the expected user experience.</li><li>Currently, the user is required to click on a row first before the selected row can be cleared.</li>|

_Please refer to the screencast below_ 

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/8bcb45c8-1be1-43d7-9424-614557c2848b

--------

- [ ] **Please consider increasing the size of the icons for 'Clear Cookie' and 'Delete All Cookies'.**

<kbd>![image](https://github.com/rtCamp/ps-analysis-tool/assets/15173772/a3cbcb6b-e481-4e3b-94ab-2d820aab9899)</kbd>

Expected Size - <kbd>
![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/f1d51ece-d58d-49f4-827a-014ab896865e)</kbd>

-----

- [x] **Please consider implementing a hover effect for the icons associated with 'Clear Cookie' and 'Delete All Cookies'.**

https://github.com/rtCamp/ps-analysis-tool/assets/15173772/db1b68c3-25a1-473c-bb3a-06f087639749

-----

- [x] **In the Application Tab, there is no pipe icon(|). Based on this observation, I believe we can replicate a similar UI for PS Tab as well.**

<kbd>![image](https://github.com/rtCamp/ps-analysis-tool/assets/15173772/0fb30abf-6796-4069-9909-27ab3c39184b)
</kbd>

-----

- [x] **Update the tooltip text from 'Delete cookie' to 'Delete selected cookie' to provide users with a clear indication that they need to select a row before initiating the deletion process.**

<kbd>![image](https://github.com/rtCamp/ps-analysis-tool/assets/15173772/5e63d33e-34d5-4bd2-b967-c3d4d035fb31)
</kbd>

----

- [x] **`Clear All Cookies Icon` - This icon needs a visual indicator to show its functionality. At present, it may appear as if the icon is inactive or disabled.**

| Application Tab | PS Tab|
|---- |----- |
| <kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/9ea001ff-bb86-42b8-a892-ca82d5e11ade)</kbd> | <kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/29e1cc8f-caba-429e-8baf-ff91f4936334)</kbd> |

---------

### Functional 🐞 

- [x] **`Clear All cookies` - The extension throws an error when attempting to delete cookies, and the page is still loading.**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/4331ff7b-505b-4105-b448-f77ea03f3ed6

-----

- [x] **Inconsistency in Cookie Deletion Functionality**

1. Removing a cookie from one table results in the removal of cookies from all tables.
2. **Cookie Landing Page** - displays 0 cookies, and the number of frames linked to cookies also shows 0. 
3. **Cookies Popup** - The Cookie Jar count does not update after deleting a cookie, and clicking on the popup does not reveal the matrix with a count of 0.
4. The delete operation is not smooth enough in terms of UX. The multiple click on "Delete All cookies" are required to perform an operation.

Please refer to the visual attached below.

|Screencast | Screenshot |
|----- |----- |
|https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/e0f6af91-ec5c-4bc6-b178-0c22bdc4b306 | ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/37fe6e00-09a1-4baf-8b70-2e5f2d68eac6) |

-----

- [X] **Unable to modify the cookie. It only allow to tap on the cookie but does not allow to modify the cookie.**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/6b05b933-91ca-4a73-9bba-7c90bc491571

-----

- [x] **Tab key accessibility for cookie modification is currently not working. This functionality should be implemented to enhance user experience.** - Created separate issue [here](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/299)

------

- [x] **Issue with Search functionality - With the current branch `(feat/cookie-modification)`, there seems to be an issue with the functionality of the cookie search. Kindly review the visual attached below for a comparison of the expected behavior versus the actual behavior.**

_PS: Left side window shows output from `(feat/cookie-modification)` and right side window shows latest stable V0.3.2_

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/a02ad68d-a8bf-443c-b6f4-105308d5b9a0

-------

- [x] **Now, able to modify the cookie but 'Enter Key' is not allowed**

----

- [x] **The hover effect show white color.**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/6714128b-4329-4b15-ae20-8cbde600c45b

-----

- [x] **There colors of the icons are not matching with Application Tab**

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/bbca6322-5c56-4f8a-a46a-609e200ec29a)

----

- [x] **`Esc` key is not working.** 

-----

- [x] **Discrepancies in single cookie deletion workflow in PSAT Extension compared to standard Application Tab**

> [!NOTE] 
> This feature is tested with codebase from `feat/cookie-modification` branch

-----

The process of deleting a single cookie in the PSAT differs from the expected behavior outlined in the Application tab. 

1. To delete a single cookie, the user should first select a specific row, at which point the delete single cookie icon becomes highlighted. By default the single delete cookie icon should be disabled. 
   
2. Upon clicking the delete cookie icon, the targeted cookie is removed, and the subsequent cookie row is automatically selected. The selection of the next cookie depends on the user's previous choice.
   
   - For instance, if the user initially selected the very first cookie, after deletion, the second cookie is automatically chosen. The single cookie delete button remains in an enabled state.
   
   - Conversely, if the user selected the last cookie, the row automatically shifts to the second-to-last row after deletion, maintaining an enabled state for the single cookie delete button.

However, in the PSAT, none of the above criteria functions as described above. Notably, the row being deleted does not get highlighted, causing confusion for users as to which cookie was deleted.

Please refer to this visual - 

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/fbd88c73-e1e4-48a5-9008-1a58c14180f7

-------

- [x] **Single cookie delete - UX needs improvment - No clear distinction about the button is disabled by default. Needs UI/U improvement**

| Tab | Screenshot |
|---- |----- |
| Application Tan | ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/2169c2a2-1593-49c4-a941-9881a50c4e64) |
| PSAT Tab | ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/9fad4c47-7ac9-42d3-beea-8b09f860ec9b) |

-----

- [x] **For the frames which does not have any cookie - both delete buttons should be disabled** 

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/b7495b4a-2dd9-481b-965f-7d8074dbbe7d

-----

- [x] **Once all the cookies are deleted from any selected frame then single delete cookie and bulk delete cookie icons should get disabled**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/0247624c-7730-42ba-9e31-e920809ae02c

----

- [x] **Selecting the blank row should disable the single cookie delete icon.**

| Tab | Screenshot |
|---- |----- |
| Application Tan | ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/d143df76-fd8b-4b0a-b1ff-6c273e6ca25f) |
| PSAT Tab | ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/bab30fe6-b0af-478b-9573-c082bb3e1fed) |

-----

- [x] **If the user keeps clicking on single cookie delete icon even after all the rows are deleted then clicking on empty row will throw an errors in console**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/602aa985-aae3-424b-9365-630095337031

-----

- [x] **Again the hover effect on enabled state is missing for single delete cookie**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/5eff1880-54c3-45a8-9393-fcf422303c69

**Comment by kjnanda** [comment]
@amovar18 Cookie Modification has been tested and will be able to test more scenarios once the edit cookie issue will be fixed.

**Comment by kjnanda** [comment]
@amovar18 There is a broken UI after the latest pull.

 | Screen case | Screenshot |
 |------- |------- |
 | https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/742fd13c-f00f-4ae4-b989-ff432f3f4845 | ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/bb71910b-2133-4b66-b446-60126dc4e018) |

**Comment by kjnanda** [comment]
@amovar18 

> Discrepancies in single cookie deletion workflow in PSAT Extension compared to standard Application Tab

This is not completely fixed. The focus of the selected row is shifted to the last row.

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/e64a8b1f-f4fd-4968-9f31-68fe093b2a60

**Comment by amovar18** [comment]
>  If the user keeps clicking on single cookie delete icon even after all the rows are deleted then clicking on empty row will throw an errors in console

The error thrown is not related if you check the console properly. Its a past error I would suggest that if you were to report an error you clear the console and check if the error is being thrown.

**Comment by kjnanda** [comment]
Yes, I had cleared the console and it only generated after I click on empty table. I guess this would be automatically handled when we will disable the single cookie delete when there is no more rows to delete.

**Comment by kjnanda** [comment]
@amovar18 

- [ ]  **Esc key is working now but PSAT Tab opens the `DevTools' Console` Tab also. The same behaviour is working smoothly with Application Tab.**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/7112d3ca-928d-4543-b467-1a712dec418b

**Comment by kjnanda** [comment]
@amovar18 Any update on subtask 2 under [this](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/265#issuecomment-1824211633)?

**Comment by maitreyie-chavan** [comment]
As we are anticipating further updates to the implementation of https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/20 feature, the issues reported here will not be valid. Closing this issue for now, and a new one will be created when https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/20 is again ready for QA.
