### ISSUE TITLE
[QA] CLI - Sitemap - Keyboard navigation is not working as expected

### ISSUE THREAD

**Issue by kjnanda** [GoogleChromeLabs/ps-analysis-tool#267]
The keyboard navigation functions correctly when checking with the URL. However, there is an issue with the same functionality when navigating the Sitemap Report.

Upon clicking on the Sitemap, using the keyboard arrows directly navigates to the inner frame of the first frame, making it challenging to return to the outer frame.

_Please make a note the same thing happens with last frame._

--------

Codebase - PR - https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/266

------

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/79d41538-7eb7-41dc-b831-f75e795b320f

**Comment by mayan-000** [comment]
Closing this for now as changes were and issue was fixed.
