### ISSUE TITLE
Add option to export the cookie list

### ISSUE THREAD

**Issue by nyb1030** [GoogleChromeLabs/ps-analysis-tool#275]
## Feature Request

**Description:**
It is similar to this issue #228 , but it would be great to have an option to export cookie table. According to the [Wiki](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/D.-Analysis-Scenarios#:~:text=instances%20of%20Chrome.-,Compare%20the%20cookies,-Identify%20the%20cookie), the developer should compare and contrast cookies between Chrome open (Chrome instance with 3P cookies enabled) and Chrome private (Chrome instance with 3P cookies disabled). However currently it is not possible to export the cookie table, which means that the developers should manually compare the cookie table side-by-side. This might be ok for sites using a few cookies, but would become impossible for any sites using several hundred cookies.

In the Application tab on DevTool, it is possible to copy & paste the table ([source](https://stackoverflow.com/questions/12908881/how-to-copy-cookies-in-google-chrome)). However, on PSAT, when trying to copy and paste in this manner, the column / row data is lost, and all data in different column falls into single column, like below:
![574eNLWr4rh7XLX](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/88608444/6279bf5b-95b9-4ce9-a048-926c383f0e35)

The best possible solution would be to have a dedicated "export to" button, but if it's difficult, the tool should offer functionality to copy and paste while sustaining the format.

**Comment by amedina** [comment]
This feature is already supported in the CLI. Not clear what use case this would enable for users using the extension. We may add this capability in later versions.

**Comment by nyb1030** [comment]
Thanks! Some partners mentioned that using command line is hard for non-technical members. I think it is important that we make this tool somewhat non-technical friendly to scale the 3PCD preparation.
Also, I have found some potentially bugs in the CLI tool version. I will file them later.

**Comment by amedina** [comment]
We are aware of a few issues with the CLI, which are being fixed and will be part of 0.4. 

Regardless, we can add a feature for exporting the cookies from PSAT in CSV format so that they can be loaded side by side on a spreadsheet to compare the results from different testing environments. We will added to the prioritization queue.

**Comment by ayushnirwal** [comment]
@amedina Yes, this can be seen as a potential feature in v0.5 release. Since, CLI does not support targeting a particular CUJ, It will be a nice addition.

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
