### ISSUE TITLE
[QA] Optimizing User Experience: Consistent UI for Enhanced Navigation in PSAT Tab

### ISSUE THREAD

**Issue by kjnanda** [GoogleChromeLabs/ps-analysis-tool#282]
The user interface (UI) for elements, particularly the search bar, 'Delete All Cookies,' and 'Delete Single Cookies,' should mirror that of the Application Tab. 

- icon
- icon size
- icon order
- place holder text

This uniformity is important for enhancing user experience (UX), as it accommodates the habits of most users who frequently access the Application Tab. Providing a consistent UI across these features will contribute to a more seamless and intuitive user interaction.

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/5e61432d-581f-4376-99c1-fa93604f3bcc)</kbd>

We can add a few more changes on top of what is mentioned above. 

- Place the cookie count to the right corner
- Filter tooltip is same for open and close state.  

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/3a977ac7-adf2-4ae5-81d8-a79a74f7ad58)</kbd>

**Comment by mayan-000** [comment]
The cookie modification issue was moved to v0.6, and all the changes made earlier were reverted in PR347.
So as of now, we have the same old UI in the extension's table top bar, and no new UI changes are present.

Closing this issue.
