### ISSUE TITLE
Huge discrepancy between CLI generated report and exported CSV

### ISSUE THREAD

**Issue by nyb1030** [GoogleChromeLabs/ps-analysis-tool#283]
**Describe the bug**
Huge discrepancy between CLI generated report and exported CSV

**To Reproduce**
1. Generate report (websites that reproduced the issue on my end: https://www.mercadopago.com.ar, https://www.rakuten.co.jp) using [CLI](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/A.-PSAT's-How-To#build-and-run-psats-cli)
2. Open the report
3. Export the report via the export button on the report
4. Import the following reports on Google Sheet (or any spreadsheet) : `affected-cookies.csv`, `cookies.csv`, `report.csv`
5. Find the discrepancies in the # of cookies below

**Observed discrepancies**
1. Discrepancy in the total # of cookies: localhost report: **21** (1P cookies x 16 + 3P cookies x 5), exported report: **79** (1P x 16 + 3P x 63)
2. Discrepancy in the # of affected cookies: localhost report: **3**, exported report: **19**

**Expected behavior**
The # of cookies in the localhost report and exported report should be the same

**Screenshots**
1. localhost report > total cookies list screenshot
![Screenshot 2023-11-20 at 11 42 00](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/88608444/7e42c79c-56b2-4835-b9f0-e7c13b8c15a1)

2. exported report > total cookies list screenshot
![Screenshot 2023-11-20 at 11 58 54](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/88608444/687cd506-e9d0-4958-bc05-6cd00e473481)

3.  localhost report > affected cookie list screenshot
![Screenshot 2023-11-20 at 12 09 25](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/88608444/5a785fd1-4e18-41eb-9ac6-78e643773c77)

4. exported report > affected cookie list screenshot
![Screenshot 2023-11-20 at 12 07 33](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/88608444/3e824539-bd02-4f34-8c34-3e69e162ffe9)

**Desktop (please complete the following information):**
 - OS: Macbook Pro Intel, Sonoma 14.1
 - PSAT version : [v0.3.2](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.3.2)

**Additional context**
- Also a minor bug that total # of cookies in the exported report > `report.csv` is wrong (it says 81 but expecting 79)
- The issue does not seem to reproduce for sites with smaller number of cookies.

**Comment by maitreyie-chavan** [comment]
Released as a part of [v0.4.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.0), closing this issue.
