### ISSUE TITLE
Affected cookies report show cookies with “Cookies Affected” = FALSE 

### ISSUE THREAD

**Issue by nyb1030** [GoogleChromeLabs/ps-analysis-tool#284]
**Describe the bug**
Affected cookies report show cookies with “Cookies Affected” = FALSE 

**To Reproduce**
1. Generate report (websites that reproduced the issue on my end: https://www.mercadopago.com.ar, https://www.rakuten.co.jp) using [CLI](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/A.-PSAT's-How-To#build-and-run-psats-cli)
2. Open the report
3. Export the report via the export button on the report
4. Import the following affected-cookies.csv and cookies.csv on any spreadsheet
5. Find that affected-cookies.csv only has cookies with the column "Cookie Affected" set to `FALSE`, which indicate the column only shows cookies that are NOT affected

**Expected behavior**
The cookies list in the affected-cookies.csv should show cookies that are affected

**Screenshots**
![Screenshot 2023-11-20 at 12 18 23](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/88608444/79c10831-b2b6-416a-8fbd-08c208617cb7)

**Desktop (please complete the following information):**
- OS: Macbook Pro Intel, Sonoma 14.1
- PSAT version : [v0.3.2](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.3.2)

**Additional context**
- The CLI localhost report shows only 3 cookies under Affected Cookies tab, but not sure which one is the source of truth because of the issue #283.

**Comment by ayushnirwal** [comment]
Fix implemented on PR #308

**Comment by kjnanda** [comment]
@ayushnirwal LGTM 👍🏻

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.4.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.0), closing this issue.
