### ISSUE TITLE
[QA] CLI Dashboard shows the frames which does not exist while analysing the site using PSAT Extension

### ISSUE THREAD

**Issue by kjnanda** [GoogleChromeLabs/ps-analysis-tool#286]
Test URL - https://timesofindia.indiatimes.com/

| Dashboard CLI [PR](https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/192) | PSAT Extension - V0.3.2 |
|---- |------- |
| ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/37bf7de1-3590-45a8-b6f0-4e0c4c0eae09) |![image (1)](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/73b75621-290c-4279-a029-19e5619a6135)

I also checked with a few more site and I found that most sites show the top(main) frame and rest comes under the Unknown Frame! 🤔 

Please share some insight on this.

@ayushnirwal could you please look into this?

**Comment by ayushnirwal** [comment]
@kjnanda If you open the this website in a newly created profile the `google-bidout-d.openx.net` does show up in the extension, which is what the CLI does. While investigating this issue I did encounter another issue where the CLI shows fewer frames when compared to the `develop` build. 
This issue has been partially fixed. CLI now generates correct data but one frame was still not being displayed in dashboard.

@mayan-000 Would you please take a look at why its happening?

**Comment by mayan-000** [comment]
Changes made, @kjnanda Can you re-test and let know?

**Comment by kjnanda** [comment]
@mayan-000 @ayushnirwal With the latest code refactoring, CLI Dashboard shows more frames than previous. However, it won't show complete set of all frames like PSAT Extension.

**Comment by ayushnirwal** [comment]
@kjnanda Some differences are to be expected due to browser environment differences in CLI and the extension.

**Comment by kjnanda** [comment]
Closing this issue as it is addressed in V0.4.0 release
