### ISSUE TITLE
[QA] Cookie Edit functionality

### ISSUE THREAD

**Issue by kjnanda** [GoogleChromeLabs/ps-analysis-tool#287]
Cookie Edit Functionality is tested considering below scenarios:

| **Test Case** | **Expected Result** |
| --- | --- |
| **Invalid Scenarios - Editable Fields** | |
| 1. Name: Invalid characters (!, $, *, empty, space) | Field does not accept invalid characters, background turns red. |
| 2. Value: Invalid data input | Field does not accept invalid data, background turns red. |
| 3. Domain: Invalid data input | Field triggers an error for invalid data. |
| 4. Expire/Max-Age Time: Empty input and other invalid inputs | Empty input defaults to "Session." Other invalid inputs trigger errors. |
| 5. HTTP Only: Invalid input (other than "true" or "false") | Only "true" or "false" is accepted. |
| 6. SameSite: Invalid input scenarios | Only "Lax," "None," and "Strict" are valid. "None" requires "Secure." |
| 7. Secure: Invalid input (other than "true" or "false") | Only "true" or "false" is accepted. |
| 8. Path: Invalid characters or inputs | Invalid characters or inputs trigger an error. |

| **General Functionality** | **Expected Result** |
| --- | --- |
| 1. Timeout for edits during site loading | Editing times out while the site is loading. |
| 2. Double-click on any cell | UI/UX similar to the Application Tab without a specific cell order. |
| 3. Immediate error reflection for wrong data entry | Errors are reflected immediately upon entering wrong data. |
| 4. Search and edit functionality | Search and edit functions work properly. |
| 5. "Cookie Accepted" display | Shows both accepted and rejected cookies with respective icons. |
| 6. Editing focus on tab switch | Focus on the editing cell is automatically removed when switching tabs. |
| 7. Changes should persist after refresh | Changes persist after page refresh |
| 8. Editing secure cookies | Secure cookies (SameSite:None and Secure:true) cannot be edited to non-secure. |
| 9. Extra rows after editing specific cookies | Editing "SameSite:None" and "Secure:true" cookies does not add extra rows after page refresh. |

---------

- [x] **1. SameSite: Editing is allowed but it does not take the value even after adding secure to "true"**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/f7e9f1dd-5e3b-4f07-87f5-e6c2a9461517

------

- [x] **2. Http Only and Secure - While editing these values checkbox should be aligned in the center**

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/9dae0583-0e0a-44da-9d1b-f1ddd9fb0a59)

------

-  ~Allow the user to add the cookies on top of the existing available cookie. If you observe the Application Tab it allows the user to add a new cookie inside any frame where as PSAT does not provide such functionality.~ Not in current scope as per [comment](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/287#issuecomment-1823870800) 

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/d91ba8a7-6634-4409-a342-dc117f509a37

-------

- [x] **3. There should be some timeout while making any edit.**

As per Application tab, once the use double clicks on any cell it stays in edit mode for a few secs only. And later it changes back to the non-edited state.

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/ab6062b3-bd83-40dd-b418-08552559f78a

--------

- [ ] **4. On double clicking the any cell it does not give the same UI/UX as Application Tab** Ref : https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/287#issuecomment-1827436698

| Feedback w.r.t Application Tab | Visual |
|----- |----- |
| It focuses on that cell with selected background based on the active there | https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/cc272606-39c9-42c6-ac75-0bf748186adc |
| Shows the string from the beginning where as PSAT Tab during editing it does not show the string the same way. So after editing the cookie there seems a change in alignment of the content.  | https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/6f0fb9bd-108c-4022-b3bc-360da8aae21f |

-----

- [x] **5. Editing the path with wrong data does not reflect the errors immediately.**

This actually applies to every edit that we make. The error should be reflected immediately which is not happening right now. 

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/e1d16e93-a81f-4892-90b4-67bc9f72e2c6

-------

- [x] **6. Editing the cookie with cookie search does not function as expected.**

```
Steps:

1. Pull the code from feat/cookie-modification branch
2. Execute npm start
3. Open new chrome instance
4. Enter the URL
5. Search cookie by its name/domain
6. Try to edit the cookie name/value/domain
7. The above fields take some predefined values and edit it
8. Check the Application Tab and it also takes those changes
```

**Expected output** - Clicking on field to edit, it should show the value from that particular cell only. It should not remember any previous modification that were made! 

Please refer to this visual 

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/102acce3-5de8-4d80-b3ab-c004cf792232

------

- [x] **7. Cookie Accepted : This column does not show empty cell for cookies not accepted. It should be ✖️ instead of empty value.**

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/9649b323-2ca9-470c-a49d-c5ca0d2701f8)</kbd>

------

- [x] **8. While editing a cookie, if the user switches from one DevTools tab to another, the focus(high lighting) on the editing cell should be automatically removed.**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/11ab08bd-683d-46cb-a69c-4dc078671bd0

---

- ~**Application Tab removes the cookie after modifying it with invalid input. The same should apply for PSAT Extension**~ Ref [Comment](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/287#issuecomment-1825265199)

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/6490e44c-e61b-40c4-91d8-29d206613cf2

----

-  ~**Expires/Max-Age - Shows wrong time for cookies**~ Invalid issue

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/f5f41abb-84b4-41b3-8b2a-ef707c6cdde6)

----

- ~**Values column shows empty for cookies not accepted**~ Invalid issue

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/6dfb9b48-1fbd-4007-96cf-1982ade7849a)

----

- [x] **9. Value column : Issue with editing**

- Editing ✅ 
- Value after editing ❎ 
- Application Tab > Value reflects ✅ 
- Throws error with changed bg color in PSAT Tab 

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/e6823716-2135-42ec-9363-2b450876c008

-----

- [x] **The Error handling UI/UX is not matching with Application Tab**

| Tab | Screenshot |
|----- |----- |
| Application Tab | ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/7c4668af-d3d8-489a-9a86-7e871e6fb438) |
| PSAT | ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/02e0f0d8-660d-484b-a889-12ec96649839) |

----

- [x] **Empty value validation check for EXP/MAX-AGE Column**

If the empty value is set for any row then Application tab sets it to `Session` where as PSAT does not sets it to session and shows the error.

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/1f665075-9713-479f-b4ae-74807d4dbfb9

-----

- [x] **Application Tab auto corrects to old value after editing any column with invalid value**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/b4232fee-1409-44c3-9401-3984ffffbdbb

------

- [x] **Issue with editing the any cookie name with empty value**

Steps:

1. Open any URL 
2. Edit any cookie name to empty value i.e. leave cookie name field blank
3. Now, Check the Application Tab if it takes all those changes
4. Refresh the page
5. Check the Application Tab
         - Application tab will show 2 rows now.
         - One with original value
         - One with edited value 
6. Check PSAT 
        - PSAT will also show 2 rows
        - One with original values
        - one with edited value **but Cookie name shows its old value and value shows empty** 

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/cbb82b33-598a-4515-a2a9-46340962327e

-----

**Comment by amovar18** [comment]
>  Allow the user to add the cookies on top of the existing available cookie. If you observe the Application Tab it allows the user to add a new cookie inside any frame where as PSAT does not provide such functionality.

This is not under the current scope will add when necessary.

**Comment by amovar18** [comment]
`Application Tab removes the cookie after modifying it with invalid input. The same should apply for PSAT Extension` cant do this because we haven't accepted the value in the case of the application tab the value was accepted and an error was thrown and then the cookie was removed.

**Comment by kjnanda** [comment]
@amovar18 I am unable to modify any column. Editing any value toggles to errored background with the latest pull.

**Comment by kjnanda** [comment]
@amovar18 Font color needs to be changed for light theme when error appears.

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/f7d760a1-17e9-426f-af2f-14da1114c6ff)</kbd>

**Comment by kjnanda** [comment]
The above issue mentioned [here](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/287#issuecomment-1831293347) is fixed.

**Comment by kjnanda** [comment]
@amovar18 Could you please check once path related editing UX issue? I don't see timeout while the site is loading.

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/ffb6aa69-aa98-4b5a-9a19-76172b38fee5

**Comment by maitreyie-chavan** [comment]
As we are anticipating further updates to the implementation of #20 feature, the issues reported here will not be valid. Closing this issue for now, and a new one will be created when #20 is ready for QA.
