### ISSUE TITLE
[QA] Inconsistency in showing this label - "This tool works best with a single tab for cookie analysis."

### ISSUE THREAD

**Issue by kjnanda** [GoogleChromeLabs/ps-analysis-tool#288]
```
Test Environment:

1. Chrome Version 119.0.6045.159 (Official Build) (arm64)
2.  PSAT Extension V0.3.2
```

1. When the tab is opened in fresh environment the popup and extension devtool fails to show the label 
2. Once the other URLs are analysed and if we come back to the first tab then popup shows the label but extension devtool still fails to show the label.

Please refer to the screenshot mentioned below.

| PSAT Extension in DevTools | PSAT Popup on very first click | PSAT Popup after analysing a few sites and coming back to same tab |
|---- |---- |---- |
| ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/bfb8bc77-a6b0-4e06-85b9-e4011d9e0787) | ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/8f82acf9-8345-456d-a2bb-ddfb2dae0b89) | ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/ce4581e5-7d56-4223-a08c-befce393fa8b) |

-----

### Some other observation

- When the URL is entered on the fresh chrome profile , it shows "Analyze this tab" button on the very first tab and and opening the second most tab loads the cookie data without showing up any button.
- Revisiting the previous tab (the very first tab) shows "Analyze this tab" button with the label "This tool works best with a single tab for cookie analysis."

Please check this video

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/c9b8cead-45ec-469e-acd5-6a61b1d52b15

**Comment by amovar18** [comment]
@kjnanda This is a known issue for which we haven't found a proper listener to handle when the browser is launched from the terminal. We will fix this as and when we find a proper listener.

**Comment by pavanpatil1** [comment]
Hi @amovar18, Verified this and the issue is not consistently reproducible. However, upon clicking the "analyze this tab" button, the "No cookies found" message briefly appears for a few seconds. 



https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/eae67085-f81e-4b6b-9650-83fe930eef60
