### ISSUE TITLE
Navigate from cookie to corresponding network request 

### ISSUE THREAD

**Issue by gagan0123** [GoogleChromeLabs/ps-analysis-tool#293]
Feature parity with DevTools capability for navigating from a Cookie in the Cookie's table to the corresponding network request in the network panel (i.e. right click on cookie, navigate).

This should expose to the user blocked cookies on network requests.

**Comment by gagan0123** [comment]
Related: #277

**Comment by maitreyie-chavan** [comment]
Released in [v0.9](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.9.0)
