### ISSUE TITLE
Search input in dark mode without hover state

### ISSUE THREAD

**Issue by fellyph** [GoogleChromeLabs/ps-analysis-tool#294]
**Describe the bug**
In the dark mode at the Cookies Data table panel, the search input doesn't have a hover state, only in light mode.

**To Reproduce**
1. Set your environment in Dark mode
2. Open Chrome DevTools
3. Go to the Cookies' data table panel
4. Pass the mouse over the search input field.

**Expected behavior**
The input should have a hover state like in light mode.

**Screenshots**
https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/330792/ed3a6079-2566-4698-90f7-582bf5380a9c

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome: 119.0.6045.159 (Official Build) (arm64) 
 - Version: develop

**Additional context**

**Comment by ayushnirwal** [comment]
PR #295 fixes this

**Comment by mayan-000** [comment]
Not closing this as of now, because it's `Develop Ready` and is to be merged to `main`.
Will be closed when merges to main.

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.4.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.0), closing this issue.
