### ISSUE TITLE
Matching Cookie Table top Bar background color matching with DevTools in Light Mode

### ISSUE THREAD

**Issue by fellyph** [GoogleChromeLabs/ps-analysis-tool#297]
**Describe the bug**
The top Bar from the Cookie Data Table panel on light mode has a different background color than DevTools, the color should match the Applications tab top Bar:

Application Tab:
![Screenshot 2023-11-22 at 13 57 16](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/330792/5861c23a-acb5-4c5c-bf47-fdfc0927309a)

Cookie Data Table:
![Screenshot 2023-11-22 at 13 57 04](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/330792/7696168f-5141-4982-9c57-270fd946fb5b)

As we can see in the screenshot above, the Extension top Bar has a gray color, the DevTools top Bar has a white color.

**To Reproduce**
1. Set the OS to light mode
2. Open the Extension
3. Go to the cookies data panel selection the analyzed URL 
4. Compare the top bar color with the Applications tab 

**Expected behavior**
The top bar at the cookies data table should have a white background, such as the application tb top bar

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser 119.0.6045.159 (Official Build) (arm64) 
 - Version: develop

**Comment by kjnanda** [comment]
@mayan-000 The added change looks good for light theme.

- [ ] However, we need to fix the same for the Dark theme as well. 

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/8b854b57-b4cc-4601-928a-a69e6dee9d6f)</kbd>


- [ ] Also, I found that while adding this fix, the hover effect of search seems not working. Could you please take a look?

**Visual**

Left shows the code from fixed PR. Right part has the stable version.

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/66b590c9-77ce-4b67-a829-4e6ac5593e7a

**Comment by kjnanda** [comment]
@mayan-000 Looks good. 👌🏻

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
