### ISSUE TITLE
Classify observed cookies across different categories

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#3]
## Feature Request

**Description:**
Capability of categorizing cooking across different dimensions:

- Origin
- Lifespan
- Purpose
  - Functional (also known as technical, essential or strictly necessary)
  - Preferences (also known as functionality)
  - Analytics (also known as performance or statistics)
  - Marketing (also known as tracking or social media)

**User Story:**
As a developer/website owner/web user, I want to get an understanding of the types of cookies being set by my site and/or my browsing activities.

**Acceptance Criteria:**
- [ ] All observed cookies are checked for presence in the cookie DB and properly labeled when displayed in the cookie list.

**Comment by sayedtaqui** [comment]
Done in https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/25
