### ISSUE TITLE
Create Privacy Sandbox API "info cards"

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#31]
## Feature Request

**Description:**
Design and implement a Privacy Sandbox API information cards providing a clear and concise definition of each API and access to the main knowledge sources. 

**Acceptance Criteria:**
- [x] Basic design of card, UI/UX
- [x] Evaluate and propose solutions for displaying the card in a popup and/or at the top of the Privacy Sandbox DevTools panel. 
- [x] Demo on empty Topics tab

**Content Example:**
| API| |
| ------------------------|---|
| Private State Tokens | Allows websites and services to evaluate a user’s authenticity without needing to know the user’s identity.   With this API, a website/service can issue a batch of Private State Tokens (renamed to Private state tokens from Trust Tokens)  to a user’s browser. The tokens are stored on the user’s browser and can then be “redeemed” by other sites and services as a signal of the user’s authenticity. |
| [Proposal](https://github.com/WICG/trust-token-api) | Public explanation for the proposed solution (Chrome) |
| [Public Discussion](https://github.com/WICG/trust-token-api) | Public questions and feedback about the proposal |
| [Video Overview](https://www.youtube.com/watch?v=bXB1Iwq6Eq4&t=3s) | Short summary video |
| [Dev Documentation](https://developer.chrome.com/docs/privacy-sandbox/trust-tokens/) | Developer documentation |

**Comment by dmdabbs** [comment]
IMO, the Privacy Sandbox dev relations team should create & manage the shared content and this extension can link to it.

**Comment by dmdabbs** [comment]
Thanks @amedina. FWIW, I'd suggest that the primary point in your explainer for a Privacy Sandbox analysis tool should be:

>* How can I ensure that my websites are still able to function properly after third-party cookies are deprecated?

Those first three are implict/subsidiary.

**Comment by sayedtaqui** [comment]
Done in https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/54
