### ISSUE TITLE
Detect use of Google Sign In (GSI) libraries and provide guidance to users

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#316]
**Description:**
Google Sign-In manages the OAuth 2.0 flow and token lifecycle, simplifying your integration with Google APIs.

The [Google Sign-In](https://developers.google.com/identity/sign-in/web/sign-in) JavaScript platform library for Web has been deprecated after March 31, 2023. [Google Identity Services for Web solution](https://developers.google.com/identity/gsi/web/guides/overview) is the new, more secure way to sign in users with Google accounts. It's easy to use and protects users' personal information.

**Motivation:**
The purpose of this feature is to implement detection of GSI libraries usage on web pages, and provide information and guidance o users to migrate to newer versions of the library, and avoid breakages due to the deprecation of third-party cookies. 

**Acceptance Criteria:**
- [x] GSI v2 is detected
- [x] Newer versions of GSI are detected
- [x] Guidance is provided to users

**Comment by amedina** [comment]
In the Insights section displaying the result of PSAT's GSI detection, guidance to users will be provided by pointing them to: 

https://developers.google.com/privacy-sandbox/3pcd/guides/identity#federated_identity

cc @gagan0123 @mohdsayed

**Comment by maitreyie-chavan** [comment]
Incorporated and released as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
