### ISSUE TITLE
[QA] CLI Dashboard > Sitemap: Confusion in sitemap report 

### ISSUE THREAD

**Issue by kjnanda** [GoogleChromeLabs/ps-analysis-tool#319]
I have observed that matrics being shown on **Sitemap > Landing page > No of Frames and No frames with associate cookies** creates more confusion.

This matrics helps when analysing the single site URL but for site map we need to showcase these data such a way that it does not.

| | Screenshot |
|--- |--- |
| Site map | ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/140cd8a4-868f-4bc4-99b6-6090cff2a06d) |
| URL | ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/6d983dcd-c897-485f-adcf-088f31a6d56f) |

Sitemap shows the no of pages, not the frames. 

For `https://www.hindustantimes.com/images/popup/sitemap/sitemap-index.xml` Sitemap landing pages shows 20 frames but if we observe the individual URL's landing page it has `7+7+7+9+17` so it not near to the count it shows!

**Comment by kjnanda** [comment]
@mayan-000 Yes, your explanation stands out valid but we need to figure it out how the same thing we can convey to the end users.

**The solution that I can think of :** We can add a tooltip which can help the user to give the clear understanding about the same. 

What do you think?

CC @ayushnirwal

**Comment by mayan-000** [comment]
Yes, the tooltip works. I will update the UI with that as per bandwidth availability.

@kjnanda

**Comment by mayan-000** [comment]
The Cookie modification issue has been moved to v0.6.
All the icons added on the top bar were reverted in PR347
So as of now, we have the same old UI on the top bar.

Due to the above reasons, I am closing this issue.

**Comment by mayan-000** [comment]
Closed this by mistake, reopened now.

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
