### ISSUE TITLE
PSAT: Insights on Potential Breakages, relevant Privacy Sandbox APIs

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#325]
## Feature Request

**Description:**
Progressively add insights components to the different PSAT landing pages and UI components.  This feature encompasses a sound set of such insights and will be address by multiple PRs. 

**Acceptance Criteria:**
- [x] GSI guidance (includes guidance from #316)
- [x] Detect specific CUJs (for known cookies, or page components) and provide guidance on PS APIs as plausible replacement building blocks

cc @gagan0123 @pradeep910 @prasadnevase

**Comment by maitreyie-chavan** [comment]
Addressed as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
