### ISSUE TITLE
Improve CLI for test automation

### ISSUE THREAD

**Issue by chrisn** [GoogleChromeLabs/ps-analysis-tool#327]
The CLI currently starts a local web server to show the analysis results. When using the tool in a test automation / continuous integration context, I'd like for it to save the report files, but not start the web server.

Similarly, if I give a sitemap URL via the CLI, it prompts me to choose the number of URLs to visit. Is there a way to set this via the CLI, so that it doesn't rely on user interaction?

**Comment by jlacher** [comment]
+1

**Comment by amedina** [comment]
Great suggestions! This is part of a piece of the work for "making PSAT's CLI CI friendly". We are prioritizing this work and expect to include in upcoming versions.

**Comment by maitreyie-chavan** [comment]
Closing this issue as most of the requests have been addressed across various releases - [v0.4.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.0) and [v0.5.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)

**Comment by chrisn** [comment]
Thank you! We appreciate your work on this.
