### ISSUE TITLE
Updates to Quick Links on landing pages

### ISSUE THREAD

**Issue by maitreyie-chavan** [GoogleChromeLabs/ps-analysis-tool#328]
## Task

**Description:**
We need to add new and update some existing items under the Quick Links section on our extension's landing pages as follow

1. [Learn more about PSAT](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki)
2. [Join the discussions](https://github.com/GoogleChromeLabs/ps-analysis-tool/discussions)
3. [Report a bug](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=)
4. [Report a breakage](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/new?assignees=&labels=&projects=&template=third-party-cookie-breakage-report.md&title=)

cc @prasadnevase

**Comment by pavanpatil1** [comment]
Hi @mayan-000, Verified the newly updated link and it is looking and working fine. 

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/080c174d-05d4-4649-b33c-7284ea7e3472)

**Comment by maitreyie-chavan** [comment]
Released as a part of [v0.4.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.0), closing this issue.
