### ISSUE TITLE
Add a possibility to accepting the usage of cookies for websites under privacy regulation

### ISSUE THREAD

**Issue by fellyph** [GoogleChromeLabs/ps-analysis-tool#330]
## Feature Request

**Description:**
Under GDPR and other privacy regulations, web applications can only set cookies after the user clicks "accept cookies". When we run the CLI, we can't bypass this check, so the CLI report doesn't capture all the cookies. 

For example:

Before accepting the cookies banner: 
<img width="1440" alt="Screenshot 2023-12-12 at 22 16 37" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/330792/1822bca9-292c-463f-ac7a-8b0ff18a7c98">

After accepting the cookies banner:
<img width="1440" alt="Screenshot 2023-12-12 at 22 17 48" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/330792/be168a71-4b56-41c0-bc31-b7393dab448a">

A report with the CLI:
<img width="1440" alt="Screenshot 2023-12-12 at 22 38 31" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/330792/66734b07-03dc-457f-8146-e345968b29e3">

The suggested solution is to create a property on the CLI, where we can set an element selector such as class, id, or property. To find and click the element responsible for accepting the cookies:

`npm run cli -- -u https://sicnoticias.pt/ -e #didomi-notice-agree-button`

or

`npm run cli -- -u https://sicnoticias.pt/ -c didomi-notice-agree-button`

`npm run cli -- -u https://sicnoticias.pt/ -i didomi-notice-agree-button`

<img width="1262" alt="Screenshot 2023-12-12 at 23 05 41" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/330792/3919fd75-7b98-4a72-9a0b-6f57dee7caf7">

**Motivation:**
This will help the CLI create some reports reproducing users accepting the usage of cookies, giving a more complete report.

**User Story:**
As a developer, I want to create reports with the CLI simulating the users who accepted the usage of cookies so that I can have a completed report.

**Acceptance Criteria:**
- [ ] Provide a set of properties to the CLI to select a specific button to be clicked for cookie acceptance.
- [ ] Have the possibility to select an element via class, id, or property

**Comment by maitreyie-chavan** [comment]
Addressed in the previous releases, closing this issue now.
