### ISSUE TITLE
Expand/Collapse toggle for filter

### ISSUE THREAD

**Issue by prasadnevase** [GoogleChromeLabs/ps-analysis-tool#332]
## Feature Request

**Description:**
As of now the user needs to collapse each filter individually. Having “Expand/Collapse All” will be useful

**Current**
<img width="886" alt="image" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/1147666/46257f82-2d45-47c7-9667-9523e85e9ab0">

**Suggested**
<img width="886" alt="image" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/1147666/4105936c-b663-46be-9a82-97e39ee086d4">

**Comment by amedina** [comment]
@prasadnevase @gagan0123 Link this to the "Uniform Filtering" issue.

**Comment by pavanpatil1** [comment]
Hi @mayan-000, Verified the PR and the Expand/Collapse All button is visible and working as expected. However, observed one thing added below: 



- [ ] In the `Retention Period` filter option, the show more link is visible but on click on it noting is loading. 


![showmore](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/4d0164eb-9740-4618-884d-8f1c1b560309)

---

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
