### ISSUE TITLE
PSAT: Enable setting "allow list" Content Policy setting directly from cookies

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#334]
## Feature Request

**Description:**
To facilitate testing site behaviors with blocked vs. enabled cookies, add the capability of updating the "allow list" Content Policy setting directly from cookies in PSAT. 

**User Story:**
As a user I want to be able to allow all cookies coming from a specific domain to be set on my device for the duration of a browsing session. This way I will be able to assess the impact of cookies blocking for specific components of my site. 

**Acceptance Criteria:**
- [x] User have the ability of right-clicking 
- [x] `chrome://settings` ➡️ `Privacy and sec security` ➡️ `Site settings` ➡️ `Additional content settings` ➡️ `On-device site data` ➡️ `Allow to save data on your device` is updated with the addition of the "pair" `<top-domain, embed-domain>`, effectively allowing cookies from `embed-domain` to be set on `top-domain`.
- [x] User can distinguish cookies that have been allowlisted
- [x] User has the ability to remove a domain from the allow list setting
- [x] Setting duration: Session

**Additional Information:**
- [x] Leverage the [chrome.contentSettings API](https://developer.chrome.com/docs/extensions/reference/api/contentSettings)

**Comment by maitreyie-chavan** [comment]
Incorporated and released as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
