### ISSUE TITLE
Reorder the sequence of Columns in PSAT's cookie table

### ISSUE THREAD

**Issue by maitreyie-chavan** [GoogleChromeLabs/ps-analysis-tool#336]
## Feature Request

**Description:**
Reorder the columns as per the following sequence

1. Cookie Name
2. Scope
3. Domain
4. Partitioned Key
5. SameSite
6. Category
7. Platform
8. HTTP Only
9. Secure

**Comment by kjnanda** [comment]
@amovar18 
How the columns will get rearranged after CDP code will be merged? As there won't be `GDPR and Cookies Accepted` column and will have 3 new columns, `Partitioned Key, Size and Priority columns`.

**Comment by maitreyie-chavan** [comment]
> will have 3 new columns, Partitioned Key, Size and Priority columns

@amovar18 please prioritize the`Partitioned Key`after `Domain` and the remaining can be added after `Secure`

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.4.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.0), closing this issue.
