### ISSUE TITLE
Baseline Topics API tab in PS Analysis DevTools Panel 

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#34]
## Feature Request

**Description:**
Implement the Topics API tab with baseline information such as the API Information Card (#31)

**Acceptance Criteria:**
- [x] Topics API tab
- [x] Add API Info Card

**Additional Information:**
- [Get to know the new Topics API for Privacy Sandbox](https://blog.google/products/chrome/get-know-new-topics-api-privacy-sandbox/)
- [Topics API Proposal](https://github.com/patcg-individual-drafts/topics)
- [Topics API Overview](https://developer.chrome.com/docs/privacy-sandbox/topics/overview/)
- [Improvements to the Topics API](https://developer.chrome.com/blog/topics-enhancements/)

**Comment by amedina** [comment]
<img width="2159" alt="Screenshot 2023-06-21 at 1 21 06 PM" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/506089/09858c0c-d33d-4096-8b5b-c5580683dd9b">

**Comment by sayedtaqui** [comment]
Created another [issue#100](https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/54) for the rest of the items. Updated the issue description for the tasks which was already completed, therefore closing this ticket.
