### ISSUE TITLE
SameSite section in Cookies Menu Element of Privacy Analysis DevTools Panel 

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#35]
## Feature Request

**Description:**
SameSite section on Cookies Menu display area, capturing behaviors demonstrated in this [demo](https://samesite-sandbox.glitch.me/) and in these [examples](https://github.com/GoogleChromeLabs/samesite-examples). 

**Acceptance Criteria:**
- [ ] Convey complete information about SameSite
- [ ] Fit into Cookies Tab UI

**Additional Information:**
- [ ] [SameSite Cookies Explained](https://web.dev/samesite-cookies-explained/)
- [ ] [Incrementally better cookies](https://datatracker.ietf.org/doc/html/draft-west-cookie-incrementalism-00)
- [ ] [SameSite Recipes](https://web.dev/samesite-cookie-recipes/)

**Comment by dmdabbs** [comment]
Suggest also a section or vocerage for use of Cookies Having Independent State (CHIPS) - https://developer.chrome.com/en/docs/privacy-sandbox/chips/.

**Comment by amedina** [comment]
@mayan-000 To review and discuss https://www.chromium.org/updates/same-site/test-debug/
