### ISSUE TITLE
Bug: Intermittently blocked cookies count is wrong

### ISSUE THREAD

**Issue by ayushnirwal** [GoogleChromeLabs/ps-analysis-tool#354]
**Describe the bug**
The cookies landing page that displays the number of blocked cookies randomly gets stuck at 0, despite the confirmation of blocked cookies in the Network Tab of Chrome's developer tools.

**To Reproduce**

1. Load the Privacy Sandbox Analysis Tool extension in Chrome.
2. Open a new instance and navigate to a website (e.g., example.com).
3. Close (if already open) and reopen the developer tools to ensure the Privacy Sandbox tab is present.
4. Observe the website, which likely involves third-party cookies, eg, https://edition.cnn.com/ .
5. Check the cookies landing page of the Privacy Sandbox Analysis Tool for the count of blocked cookies.
6. Navigate to the Network Tab and filter the results by blocked response cookies.
7. Notice the discrepancy between the actual blocked cookies in the Network Tab and the zero count displayed on the cookie's landing page.

**Expected behavior**
The expected behavior is that the cookies landing page counter of the Privacy Sandbox Analysis Tool accurately reflects the number of third-party cookies blocked by the browser, in accordance with the data shown in the Network Tab.

**Screencast**
https://www.youtube.com/watch?v=cCHg9rT5uyQ

Desktop (please complete the following information):

OS: Pop!_OS 22.04 LTS x86_64
Chrome Version: Version 120.0.6099.109 (Official Build) (64-bit)

**Additional context**
This issue seems to occur randomly and poses a significant problem in accurately debugging and analyzing third-party cookie behavior in Chrome.

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.4.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.0), closing this issue.
