### ISSUE TITLE
MacOS Chrome Launcher Script missing `.zshrc` Handling and Script Sourcing

### ISSUE THREAD

**Issue by gagan0123** [GoogleChromeLabs/ps-analysis-tool#356]
**Describe the bug**
When launching the Chrome launcher script on MacOS as per the instructions in the [Wiki](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/Evaluation-Environment#spinning-chrome-instances-from-command-line), encountered issues if a **`.zshrc`** file does not exist in the home directory. Additionally, the **`chrome_launcher.sh`** script does not automatically source, requiring us to manually source it or open a new shell for the commands to become available.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'Terminal' on MacOS.
2. Enter the command **`curl -sL https://rt.cx/psat | bash`**.
3. Notice the errors related to the missing **`.zshrc`** file (only occurs if that file does not exist).
4. Attempt to run the command **`chrome-default`** to launch Chrome.
5. See the error that commands are not found or available.

**Expected behaviour**
The expected behaviour is that after running the script, Chrome laucher commands should be available immediately without the need for manual sourcing or opening a new shell. Additionally, there should be a check for, when a **`.zshrc`** file is not present to avoid errors.

**Screencast**

[![Screencast](https://img.youtube.com/vi/h_15xXDZmU8/maxresdefault.jpg)](https://www.youtube.com/watch?v=h_15xXDZmU8)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: Version 120.0.6099.129 (Official Build) (arm64)
- ZSH: zsh 5.9 (x86_64-apple-darwin23.0)

**Comment by MiteshShah** [comment]
```
wget -qO /tmp/psat https://rt.cx/psat && source /tmp/psat
```

This will do the trick

**Comment by gagan0123** [comment]
As per the discussion with @MiteshShah, we concluded that adding help instruction after the install script finishes is the best solution. So added help text as mentioned here: https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/211#issuecomment-1888476616


![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/1535505/4fcd4a3e-87a3-4c05-b749-23cbb2ebf95e)

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
