### ISSUE TITLE
Enhancements to Streamline and Optimize the PSAT CLI

### ISSUE THREAD

**Issue by gagan0123** [GoogleChromeLabs/ps-analysis-tool#360]
**Description:**
Enhance the CLI of the Privacy Sandbox Analysis Tool (PSAT) with specific improvements to streamline its usability and functionality with the extension. The proposed changes include altering the order of columns, modifying prompt behavior, ensuring relative path functionality, and adding a new argument to control technology scanning.

**Motivation:**
These enhancements aim to align the CLI presentation with the PSAT extension, reduce unnecessary user prompts, support user flexibility in file path input, and provide more control over scanning features. This will improve the user experience, make the tool more efficient, and provide users with a more customizable and streamlined tool.

**User Story:**
As a developer or analyst using the Privacy Sandbox Analysis Tool, I want an optimized and user-friendly command-line interface so that I can perform analyses more efficiently and with greater control over the tool's features.

**Acceptance Criteria:**

- [x]  Change the order of columns in the PSAT CLI to match the PSAT extension.
- [x]  Remove the prompt asking "How many URLs to analyze" and replace it with a command-line argument for optional user definition if/when needed by the user.
- [ ]  Ensure the PSAT CLI argument that accepts the path of local CSV and XML Sitemaps is compatible with relative paths.
- [x]  Add an argument to bypass technology scanning when passing XML sitemap or CSV list of URLs for scanning, extending the existing functionality for single URL scanning.

**Comment by ayushnirwal** [comment]
Items 1,2 and 4 in the acceptance criteria are added by PR #362.

**Comment by ayushnirwal** [comment]
> Ensure the PSAT CLI argument that accepts the path of local CSV and XML Sitemaps is compatible with relative paths.

Relative paths w.r.t project root directory works fine. So when running the script from the project root directory, it should work fine.

If the user is in some folder other than the root folder, the `npm run` commands bubble up to the `package.json` to find the script. There is no real way that npm provides to know from what directory npm call comes.

**Comment by gagan0123** [comment]
@ayushnirwal 

We can continue using the existing relative path that is from the project root directory and skip resolving to the current directory from where the command was executed as I also think it will require a workaround/patch work to get it working by somehow passing in the current working directory even before `npm run` reaches to `package.json` looking into the parent directories.

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
