### ISSUE TITLE
[QA] [Enhancement] Allow full string copy when complete string is not visible

### ISSUE THREAD

**Issue by kjnanda** [GoogleChromeLabs/ps-analysis-tool#366]
## Task

**Description:**
This [PR](https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/365) enables the copy-paste functionality using the key board shortcuts. As per the current implementation, it only copies the visible string. 

So when the complete string is not visible, it does not copy the truncated characters or the full string. We should handle this case. 

**Related Issue:**
https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/261

**Visual**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/ea56bb73-3386-4ce6-b80c-22066c5c383d

**Comment by mayan-000** [comment]
This [commit](https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/365/commits/adcab0233bc33b9aeae8530f0c7bbe047feebb0a) handles the mentioned case.

Can we consider closing this issue?
@kjnanda

**Comment by kjnanda** [comment]
Closing this as mentioned [here](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/366#issuecomment-1873358787)
