### ISSUE TITLE
Incorrect Highlighting of Blocked Cookies

### ISSUE THREAD

**Issue by gagan0123** [GoogleChromeLabs/ps-analysis-tool#369]
**Describe the bug**
Observed discrepancies in the highlighting of blocked cookies. Certain cookies fail to be marked as blocked despite network requests clearly indicating their blocked status. This issue manifests unpredictably, with varying cookies affected upon each page refresh.

**To Reproduce**

1. Open Privacy Sandbox Panel.
2. Enter the site URL that you want to analyze.
3. Observe the cookies being set and their respective highlights in the Privacy Sandbox Panel's Cookies section.
4. Notice that some third-party cookies are not highlighted as blocked, despite being blocked according to the network tab.
5. Verify the same in the network tab.
6. Reload the page and observe changes in cookie highlights, noting inconsistencies.

**Expected behavior**
All cookies that are blocked should consistently be highlighted as such. There should be no random variations in the highlighting of blocked cookies upon page reloads.

**Screenshots**
1. In PSAT Panel check the highlighted cookies.
![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/1535505/d8e65b05-ab15-4d3d-955e-90b9f529a5b9)
2. Observe the same cookies in the network tab
![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/1535505/01ce7c56-9abd-4d51-8b2d-1f305a7e596f)

**Screencast**
[![Screencast](https://img.youtube.com/vi/E7PCBjU762g/maxresdefault.jpg)](https://youtu.be/E7PCBjU762g)

**Desktop (please complete the following information):**

- OS: MacOS 13.6.3 and Pop!_OS 22.04 LTS
- Browser: Google Chrome 
- Version: 120.0.6099.129 (Official Build) (64-bit) 

**Additional context**
The issue occurs randomly for different cookies on multiple reloads.

**Comment by pavanpatil1** [comment]
Verified this but was unable to replicate the issue. Also, we've transitioned to the complete CDP. Therefore, closing this issue.
