### ISSUE TITLE
Enhanced filter settings persistence

### ISSUE THREAD

**Issue by gagan0123** [GoogleChromeLabs/ps-analysis-tool#371]
Refine the PSAT extension's filtering capabilities to support the persistence of filter settings across multiple frames.

**Comment by prasadnevase** [comment]
#332 can also be part of this.

**Comment by kjnanda** [comment]
Since Issue #396 is Epic, I am adding the issue regarding the `Filter's persistent state` here.

@mayan-000 Please check the below issues.

- [ ] [Filter icon should not be enabled for empty table.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/396#issuecomment-1891754916)

**Comment by kjnanda** [comment]
### Filter icon should not be enabled for empty table.

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/ad1e7be4-77fe-44a5-b947-7ce8597535e8

**Comment by mayan-000** [comment]
WRT https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/396#issuecomment-1891754916

Acceptance criteria 5 requires it.
@kjnanda

**Comment by kjnanda** [comment]
Oh! Sorry that I missed that part!

**Comment by kjnanda** [comment]
### Blocked Reasons shown in filters without corresponding data present

I have found the strange behaviour while checking the filters values for "Blocked reasons". While the filters display multiple reasons under 'Blocked reasons,' but **when I apply the filter, no results are shown in any of the frames.** And those blocked reasons do not appear on the Cookies Landing Page too. If there is no corresponding data for the blocked reasons, why are they visible in the filters?

As shown in the below visual - 

There are total 4 blocked reasons under filter value for each frame. While cookies landing page shows only 2 for which the data is present. 

 Cookies with **ExcludeSameSiteUnspecifiedTreatedAsLax** and **NotOnPath** blocked reason do not have any data nor they are present on Cookies landing page.

----

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/3b0e48ea-fa26-4404-9c68-8f464e6c08cd

----

CC @amovar18

**Comment by kjnanda** [comment]
@amovar18 Added changes are working as expected.

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
