### ISSUE TITLE
[QA] UI doesn't revert to original style after users click Toggle All and repeats the action

### ISSUE THREAD

**Issue by kjnanda** [GoogleChromeLabs/ps-analysis-tool#374]
**To Reproduce**

1. Open PSAT from DevTools
2. Visit any frame
3. Right click on any column header
4. Click on "Toggle All" option
5. Now, there will be only on column present with "Name" 
6. To get all the columns back, again right click on "Name" column and click on "Toggle All" option
7. Observe UI which is completely distorted.

**Expected behavior**
The table columns should get its original style

**Screenshots**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/8092f5a0-522f-48a4-b1de-acb5b4e4c5ab

```
Test Environment
1. Chrome - New instance
2. Chrome version: - Version 120.0.0.0 (arm64)
3. OS - MacOS (arm64)
4. PSAT - V0.4.0

```

**Comment by kjnanda** [comment]
@mayan-000 Could you please check the below scenario where I have tried to show case the use case of toggling the random columns and how it shrinks the `Domain` columns width. 

**Visual**
https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/e490428f-6558-4bc8-a06f-491d32c4b962

**Screenshot**

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/3ade9df7-6e6e-4840-b037-67fe79a848d2)</kbd>

**Comment by kjnanda** [comment]
@mayan-000 This looks good now.

**Comment by kjnanda** [comment]
@mayan-000 

For `CLI` I accidentally came to this scenario and found that UI fails to revert back to it original style while toggling the columns otherwise it looks. 

**Please check the below visual.**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/5489eb85-0be3-429b-8655-c03acb35000b

**Comment by kjnanda** [comment]
@mayan-000 The issue mentioned here seems working fine now. However, I have found that with the latest code pull, the vertical scroll bar is missing from PSAT Extension along with CLI. 


https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/f8695c65-1d4d-4bff-b6d2-f4b18c757469

**Comment by pavanpatil1** [comment]
- [ ] The table border is not properly visible the horizontal scroll is present. 

**Steps to reproduce:** 
Open any frame and do the horizontal scroll. 

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/321e4a6f-598d-4a78-90fd-3d6432fa16bf)





---


- [ ] The blank table is visible for few seconds even though the cookies count and cookies are present while loading the page.  

**Steps to reproduce:** 
1. Open any site and visit any site. 
2. Observe on the first frame for first few seconds the cookies table will not shown. 

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.01.30-13_02_14.webm](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/b53ed471-b0c9-47b9-ae30-82af41d367a1)

**Comment by kjnanda** [comment]
This has been addressed in V.0.5.0 Release.
