### ISSUE TITLE
Enhancement: Add `Cookie Blocked` filter and make UI/UX changes to filters.

### ISSUE THREAD

**Issue by mayan-000** [GoogleChromeLabs/ps-analysis-tool#377]
During the last implementation, the "Blocked" filter was removed and replaced with the "Cookie Blocked Reasons"
 filter. The idea was that users could use the second filter to access blocked cookies data. However, considering the use case, some users might want to see all blocked cookies regardless of the reason for blocking. In this scenario, the "Blocked" filter would be very beneficial.

Additionally, a few UI/UX changes are proposed for the Cookie Blocked Reasons filter. These changes include making it dynamic, alphabetically sorting the options, and renaming it from "Cookies Blocked Reasons" to "Blocked Reasons". Furthermore, the 'i' icon will be removed.

**Acceptance Criteria:**
- [x]  Introduce a static "Blocked" filter (value: True, False) to handle issue #335.
- [x]  Show only the blocked reasons that are actually used dynamically.
- [x]  Ensure that dynamic filters are sorted alphabetically.
- [x]  Rename "Cookies Blocked Reasons" to "Blocked Reasons" and remove the 'i' icon.

Related https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/371

**Comment by kjnanda** [comment]
@mayan-000 

- [ ] **When the blocked cookies will not present, `Blocked Reasons` filters won't show any items under it.** Is there any other way we can handle this scenario? As of now, the "▸" or "▾" always present based on persistent state from previous frame. 

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/898caa55-443e-4ee1-86e3-f1c5fad09364

**Comment by amedina** [comment]
Rather than having a separate filter option for Blocked/non-Blocked cookies, we can add an `All` option to the `Block Reasons` filter dimension, allowing developers to filter all blocked cookies. 

This option should be "mutually exclusive" with respect to the other components in the blocked reasons; that is, if `All` is checked, any other blocked reason check box set must be unset, and if any blocked reason option is set, then `All` should be unset.

**Comment by mayan-000** [comment]
PR #447 will add the `All` filter value to the `Blocked Reasons` filter.
@amedina

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
