### ISSUE TITLE
[QA] - Navigation timeout error is displayed in the CLI 

### ISSUE THREAD

**Issue by pavanpatil1** [GoogleChromeLabs/ps-analysis-tool#378]
In the CLI, the navigation time out error is displayed randomly. It observed that while executing the CSV file or with the -ul flag if more than 5URL's are passed the error is displayed.  

Error: `throw new Error('Execution context was destroyed, most likely because of a navigation.');`

- Tested without -ul flag, it works fine.
- Tested with -ul 2 it works fine.
- Got error on -ul 5 value.

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/0fa41bf0-1079-427d-96fe-f1958f9325b1)

**Comment by prasadnevase** [comment]
@ayushnirwal & I tried to reproduce this but could not.

@pavanpatil1 - if you could try again and observe any specific steps to reproduce that will be helpful.

**Comment by pavanpatil1** [comment]
Hi @prasadnevase, There is no as such steps to reproduce this issue. It observed very randomly. 

I tried to reproduce this again but seems not able to replicate it now.
