### ISSUE TITLE
[QA] Discrepancy in PSAT Cookie w.r.t. Application Tab

### ISSUE THREAD

**Issue by kjnanda** [GoogleChromeLabs/ps-analysis-tool#379]
# Revisiting another round of QA for V0.4.0 as requested

Scenarios Observed so far :

Observed Scenarios:

```
1. Occasionally, PSAT displays only a subset of cookies, while the rest appear in alternative frames such as 'Unknown Frames.'
2. At times, PSAT successfully shows all cookies within its dedicated frame.
3. PSAT experiences delays in presenting the remaining cookies. and sometimes, the remaining cookies fail to appear altogether.
4. Notably, certain frames within PSAT display cookies that are absent in the Application Tab.
```

---

- [ ] **PSAT does not show complete set of cookies as Application Tab.**

Test site - `https://edition.cnn.com/` 

It is been observed that for `https://acdn.adnxs.com` frame only some cookies were missing. Application tab shows all the cookies but those all cookies were not present in PSAT Extension. 

**Screenshots**

| Application Tab | PSAT |
|--- |---- |
| ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/d191c42b-56cc-475c-abfc-8f1cfb30166e) | ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/24f80578-3e91-4836-85de-7a99d4349b36) |

Now, further investing this issue I have found -

| Observation | Screenshot |
|--- |--- |
| Those missing cookies were present under `Unknown Frames` as shown in the screenshot below. | ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/2ed616bf-a4fc-4465-a03c-218d0e2ba583) |
| The cookies take quiet a long time to appear. | https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/5500a3a0-1e45-4cfe-ad41-af83da860c62 | 
| After a few seconds I was able to get all the cookies in this frame | ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/ccc12dcc-6003-445a-8b43-bca28c1594a8) |

------

- [ ] **Some more discrepancy as mentioned above for other frames**

| Frame name  | Application Tab | PSAT |
|---- |----- |---- |
| https://assets.bounceexchange.com | ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/c673dd82-86f0-4c07-89f6-9e074a88031f) | <img width="1470" alt="Screenshot 2024-01-02 at 12 49 23" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/951e3556-588c-47f4-8321-4e9162878a85"> |

-------

- [ ] **PSAT Shows more cookies than Application Tab**

| Frame name  | Application Tab | PSAT |
|---- |----- |---- |
| https://s.amazon-adsystem.com | ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/7b5f0b50-ccf4-431c-bb27-0cce2b67d2e0) | ![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/6d83e0b8-c7e7-41fc-9a50-510da80b3f92) |

- [ ] **PSAT - There are some frame which has cookies in it where as Application Tab does not show cookies for the same.**

----

**Comment by amovar18** [comment]
@kjnanda Some of these might be solved once performance fix branch is merged to develop.

**Comment by pavanpatil1** [comment]
Cross-verified it with v0.5.0 and able to reproduce the issue 

> PSAT does not show complete set of cookies as Application Tab.


Application Tab  |  PSAT tab
:----------------:|:-------------------------:
![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/829916c1-511a-41f7-bf93-0bc05006d9c7)|![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/eb87548e-a900-4870-8d42-df9125d8b092)

**Comment by maitreyie-chavan** [comment]
@pavanpatil1 Please could you re-test against the [v0.6](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.6.0) release?

**Comment by pavanpatil1** [comment]
Hi @amovar18, Still able to see some discrepancy with the application tab. 


Application Tab          |  Privacy sandbox tab
:----------------:|:-------------------------:
![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/af705890-51bd-4326-9c16-59111ea8dfd2)|![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/5c9dd008-b062-4acd-911f-995914aa598f)



---

Application Tab          |  Privacy sandbox tab
:----------------:|:-------------------------:
![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/97938ad2-58dc-4609-84ff-18dd2ebc5853)|![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/61d7005c-59ae-4333-84e4-5d9c77fba270)
