### ISSUE TITLE
[QA] [Regression] The filter icon becomes disabled when search result is not found

### ISSUE THREAD

**Issue by kjnanda** [GoogleChromeLabs/ps-analysis-tool#385]
Steps:

1. Open any URL
2. Click on 'Analyse this tab' button
3. Now, this will load the frames
4. Click on any frame from the sidebar 
5. Now, add any random search string for which the relevant result is not present in the table
6. Observe that the filter icon gets disabled when the search string is not present.

> [!NOTE]
This works as expected for PSAT V0.3.2

-----

**Screencap**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/455a362d-f9f2-4f37-b283-272122904bdb

------

```
Test Environment:

PSAT Extension Version - 0.4.0
Browser Chrome Version 120.0.6099.129 (Official Build) (arm64)
MAC 13.5.2 (22G91)
```

**Comment by maitreyie-chavan** [comment]
Addressed as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
