### ISSUE TITLE
PSAT: Provide switch to turn PSAT's debugging capabilities on and off

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#398]
**Description:**

Add capability to tun on and off PSAT's debugging capabilities (i.e. "switch" of CDP). This would remove certain features (i.e. showing the blockning  reasons) and will also allow the use to close the Warning Info Bar. 

**Motivation:**

PSAT provides a growing number of features and only some of them leverage the CDP to gather network and browser data to help analyze and debug the behavior of cookies during browsing sessions. Leveraging CDP causes Chrome to display a Warning Info Bar informing the user that PSAT is debugging the browser. 

The purpose of this feature is to provide the option to switch the debugging  capabilities of PSAT on and off, allowing developers to turn them on when starting a debugging session and turn them off when those sessions end. 

**Acceptance Criteria:**
- [ ] There is a Settings section on PSAT sidebar with the option to "Turn PSAT debugging on"
- [ ] PSAT provides an effective mechanism for switching debugging functionality that requires CDP
- [ ] User is not exposed to the low level details regarding the use of CDP
- [ ] PSAT UI's seamlessly updates upon switch selection (on/off)

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.4.2](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.4.2)
