### ISSUE TITLE
Create "view" card with observable cookie information

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#4]
## Feature Request

**Description:**
Context: Privacy Sandbox DevTools panel's Cookie Analysis tab. For any given cookie selected from the set of observed cookies, display a "Cookie Card" showing detailed information from its configuration and from other sources such as cookies databases. 

**User Story:**
As a developer/website owner/web user, I want to get as many details about the cookies been set in my browser.

**Acceptance Criteria:**
- [x] Name: The name of the cookie.
- [x] Value: The value of the cookie.
- [x] Domain: The domain that the cookie is associated with.
- [x] Path: The path on the domain that the cookie is valid for.
- [x] Expiration date: The date and time at which the cookie will expire.
- [x] Secure: Indicates whether the cookie should only be sent over secure connections.
- [x] HttpOnly: Indicates whether the cookie should be accessible to JavaScript.
- [x] SameSite: Indicates whether the cookie should be sent with cross-site requests.

**Comment by amedina** [comment]
Rough perspective:
 
<img width="1494" alt="Screenshot 2023-06-06 at 2 55 47 PM" src="https://github.com/GoogleChromeLabs/cookie-analysis-tool/assets/506089/cabc09bf-bca0-4e83-ae1b-aeab8ac60d82">

**Comment by sayedtaqui** [comment]
Done in https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/46
