### ISSUE TITLE
Optimize code for request and response parsing for cookie data.

### ISSUE THREAD

**Issue by mohdsayed** [GoogleChromeLabs/ps-analysis-tool#404]
## Task
Epic: https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/380

### Description:
We perform multiple parsing and asynchronous operations in each request/response to obtain cookie data, which may accumulate to cause a significant delay. This task is to review and optimize these operations as much as possible to improve performance and reduce the overlay delay.

Since, the code optimization is only limited to an extent, as we anyway will have to do the parsing and other async operations. It would be worth seeking possible options to create a new thread (Worker) from DevTools (as we cannot create new Workers from service worker) to offload the heavy work and reduce stress on the service worker. Though it may complicate things, as we will have to message passing from Service worker  → DevTools → New Worker. We would want to try it once and measure the performance for a significant improvement, worth the complication.

Related Issue: 
https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/403, https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/405

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
