### ISSUE TITLE
Increase concurrency for the promise queue to reduce processing time

### ISSUE THREAD

**Issue by mohdsayed** [GoogleChromeLabs/ps-analysis-tool#405]
## Task
Epic: https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/380

### Description

As described in https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/403 and https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/404, we have to use a promise queue with `concurrency: 1` to handle multiple requests/response which adds up to increase the overlay delay of rendering cookies data. This task is to do the actual implementation of the solution proposed in https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/403 and increase `concurrency`. Please note that this task should only be started after the optimization work in https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/404 for better performance testing results.

**Related Issue:**
https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/403 , https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/404

**Comment by maitreyie-chavan** [comment]
Addressed as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
