### ISSUE TITLE
Is there a way to disable the popup?

### ISSUE THREAD

**Issue by zinkohlaing** [GoogleChromeLabs/ps-analysis-tool#406]
## Feature Request

**Description:**
There's a popup that says "Privacy Sandbox Analysis Tool" started debugging this browser every time I open a new tab or browse new page. Is there a way to disable this as it is getting a bit annoying. Thanks!

**Motivation:**
To improve the user experience of using the tool.

**User Story:**
As a normal user, I want the popup not to be so intrusive so that my browsing experience can be improved..

**Acceptance Criteria:**

The popup is disabled and I can use the tool only when I need to.

**Additional Information:**
![New Issue · GoogleChromeLabs:ps-analysis-tool 2024-01-08 10-47-02](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/13776707/8e82b57b-f3bb-405b-ab8b-0c9f64827f8d)

**Comment by amedina** [comment]
Thanks for reaching out @zinkohlaing!

The displaying of that info bar it is a consequence of PSAT using the Chrome DevTools Protocol (CDP) to be able to gather and process cookie-related data (e.g. determining cookie blocking and reasons for blocking). 

For v0.4 the recommended approach is to enable PSAT as a debugging tool to understand  cookie and PS APIs behaviors, and in search 3PCD breakages, and disable it when no debugging is being done. See this [PSAT's Wiki page](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/PSAT-Debugging) for more details. 

For upcoming versions (hopefully as soon as v0.5), we are adding "switching functionality " in PSAT to turn the Chrome DevTools Protocol on and off. When it is on, the message will be displayed, and not when it is off. It will be turned off by default, and when developers want to get deeper information about, for example, the reasons why cookies are being blocked, it can be turned on. 

Will close this issue and you can follow the progress of this feature as it is being tracked in issue [#398](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/398).

**Comment by amedina** [comment]
Hi @zinkohlaing, this issue has been addressed and PSAT has been upgraded in the Chrome Web Store.
