### ISSUE TITLE
No clickable UX objects in the pop-up - UX issue

### ISSUE THREAD

**Issue by henkvancann** [GoogleChromeLabs/ps-analysis-tool#428]
### Situation of use
I hit the PSAT tool button in the button bar of my browser.
#### Result
![Screenshot by Dropbox Capture](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/479356/f504e642-ad36-420e-8a54-b88e5f7f5f1c)

#### Remark 1:
Inspect cookies in the "Privacy Sandbox" panel of DevTools -> why is there no link where I can click on in this pop-up?

#### Remark 2:
The  (i) information sign after "3-rd party cookies" isn't clickable. User expects it to be clickable.

#### Remark 3: 
Where is the explanation / help text or button to click on or when I hoover over elements? This pop-up is stale...

#### Remark 4:
Why isn't there anything I can click on in this pop-up?

### Suggestion: Have a UX review of this main pop-up in your tool?

**Comment by milindmore22** [comment]
Hello @henkvancann thanks for your input! I appreciate your suggestions. We've addressed your points in the previous comment.  I'm going to close this issue now, but please don't hesitate to create a [new support discussion](https://github.com/GoogleChromeLabs/ps-analysis-tool/discussions/new?category=support-forum) if you have any further questions about the PSAT in the future.
