### ISSUE TITLE
[QA] - CLI - Add Blocked Reasons

### ISSUE THREAD

**Issue by pavanpatil1** [GoogleChromeLabs/ps-analysis-tool#437]
- [The Partition key column name is not properly visible](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/437#issuecomment-1903488580)

- [Helper text should be visible on the Cookie summary page. ](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/437#issuecomment-1903488766)

- [Report download button is not working. ](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/437#issuecomment-1903488917)

cc: @ayushnirwal

**Comment by pavanpatil1** [comment]
The Partition key column name is not properly visible. Need to resize the column then the name is visible. width is very less due to that the column name is not readable. Even if there is no data in the column the column name should be properly visible. 

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/5562d29e-f0c9-4609-8d95-4c37bf79421e)

**Comment by pavanpatil1** [comment]
On the Cookie Summary page, there should be "i"(helper text) should be visible similar to extension summary page.

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/71bfe69c-f0ae-4caa-ad38-c4f40a8e2bdc)

**Comment by pavanpatil1** [comment]
On click on Download report button, the error is visible 

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/9e0cb689-88b5-4fae-95bb-9bd4cb5de9c2)

**Comment by ayushnirwal** [comment]
- [Helper text should be visible on the Cookie summary page. ](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/437#issuecomment-1903488766)

- [Report download button is not working. ](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/437#issuecomment-1903488917)

Both of the items mentioned above are now fixed in the PR #435

**Comment by ayushnirwal** [comment]
- [The Partition key column name is not properly visible](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/437#issuecomment-1903488580)

This item will be fixed by PR #401

**Comment by pavanpatil1** [comment]
Hi @ayushnirwal, In the output.csv file the `Partition key` column is not visible.



![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/cc2fe9d4-5c5b-4e2b-a55d-95f04cd7ec65)

---

Also, the blocked reason is visible in the `affected cookies` as well. So `Partition key` column should be available in affected cookies table as well? 


![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/309ad4c9-0a0e-41e6-a233-cab357f56ee7)

**Comment by pavanpatil1** [comment]
Verified the above fixes and those seems fixed and working fine. 

cc: @ayushnirwal

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
