### ISSUE TITLE
[QA] - Order of column values are not matching in CLI cookie report

### ISSUE THREAD

**Issue by pavanpatil1** [GoogleChromeLabs/ps-analysis-tool#439]
In the CLI report, inside cookies.csv file the cookies values are not matching with the column for `Same Site` and `Values` column. 

**Steps to reproduce:** 
1. Download the report. 
2. Open the cookies.csv file and observe the values of `same site` and values column

![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/96882654-ceec-4ac0-8f30-e740691aca54)

@ayushnirwal

**Comment by maitreyie-chavan** [comment]
Addressed as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
