### ISSUE TITLE
[QA] Issue with multi tab environment when extension is reloaded

### ISSUE THREAD

**Issue by kjnanda** [GoogleChromeLabs/ps-analysis-tool#462]
Consider the scenario as mentioned below.

**Scenario: User is opening the multiple tabs, enabling multi tab processing from settings and reloading the extension. Now, observe the behaviour on how cookies are being loaded on each tab.**

_This should be QAed under the fresh chrome profile._

```
Steps:

1. Open chrome://extesions page
2. Now, open 3-4 tabs with different URLs
3. By default, it will be in single tab processing mode
4. Toggle the multi tab environment from settings
5. Optionally, enable the CDP switch to see the blocked cookies too
6. Now, reload the extension 
7. Go back to the each single tab and observe that there should be "Refresh Panel" button
8. Click on that button
9. Observe that on most cases either the cookies won't and cookie count stays on `0` or randomly less cookies will appear, may be 2,4 cookies until you explicitly refresh each and every single page
```

------

Please refer to the visual below.

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/b6fbcfc1-d2e9-4d70-98d0-7de34e4ba0d1

----- 

```
Test Environment: 
- Chrome - 121.0.6167.85 (Official Build) (arm64) 
- Branch - feat/optimize-iterations
```

**Comment by pavanpatil1** [comment]
Verified the issue and it seems fixed and working fine. 

[multitab-fix.webm](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/2f5957d1-a665-4798-a31f-e0e46a90f1cc)


cc: @amovar18

**Comment by amovar18** [comment]
Closing this issue since it has been fixed in past releases.
cc @maitreyie-chavan
