### ISSUE TITLE
PSAT Extension Triggers failure of Attestation check for Topics

### ISSUE THREAD

**Issue by gagan0123** [GoogleChromeLabs/ps-analysis-tool#477]
**Describe the bug**
An attestation error occurs when using the PSAT extension in conjunction with the Privacy Sandbox APIs enabled in Chrome.

**To Reproduce**
1. Open a Chrome browser instance with the PSAT extension installed and enabled.
1. Open `chrome://flags`
1. Enable `Privacy Sandbox Ads APIs` and `Privacy Sandbox Proactive Topics Blocking`
1. Navigate to a website, such as https://example.com or another site.
1. Observe that an attestation error appears in the developer console along with the source of the issue pointing to PSAT Extension.
1. Disable the PSAT extension and reload the page.
1. Notice that the attestation error no longer appears, indicating a link between the PSAT extension and the error.

**Expected behavior**
When browsing websites with the PSAT extension enabled, no attestation errors should occur.

**Screenshots**
![Flags](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/1535505/89eede4b-0acf-40aa-aebc-8a7f8cc79493)
![Error](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/1535505/535a8564-c5fa-48dd-a38e-a67013cd5d21)

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS x86_64
 - Browser: Google Chrome 121.0.6167.85 (Official Build) (64-bit) 
 - Version of PSAT Extension: 0.4.2

**Comment by maitreyie-chavan** [comment]
Addressed as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)
