### ISSUE TITLE
Display cookie analysis summary in extension icon pop up 

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#5]
## Feature Request

**Description:**
Provide a cookie-usage summary for the tab currently in focus, which will be updated as a page continues loading and navigation actions are taken. 

**User Story:**
As a developer/website owner/web user, I want to understand the status of cookies for a given web page at a glance. 

**Acceptance Criteria:**
- [x] Summary of 1P and 3P cookies is displayed when clicking on the icon pop up.

**Comment by sayedtaqui** [comment]
@ayushnirwal some suggested improvements:

1. Add a count for each category of cookies.
2. Include a message at the bottom suggesting opening DevTools to inspect cookies. Also please check if a way to programmatically open DevTools is by clicking a link from the popup.

<img width="786" alt="image" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/6297436/911761f4-edaa-44e3-94b2-4ee371b039a0">

**Comment by sayedtaqui** [comment]
Done in https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/53
