### ISSUE TITLE
Regression Misc Fixes - Post v0.5.0 Release

### ISSUE THREAD

**Issue by maitreyie-chavan** [GoogleChromeLabs/ps-analysis-tool#509]
# Description:

## Library Detection:

- [ ] The “Known Breakages” section takes an indefinite amount of time to load when you visit a page that doesn’t exist. It will continue loading even if you subsequently visit another page. (It’s because the underlying API we rely on to get the resources breaks in this case and the Promise never resolves.)

- [x] Sometimes it gives false positive results on [edition.cnn.com](http://edition.cnn.com/)

## Zero Cookies:

- [x] After some inactivity on the browser, when we try to analyze cookies from the extension, the cookies count becomes zero. It will work after we close and open the DevTool.

**Comment by mohdsayed** [comment]
> Sometimes it gives false positive results on [edition.cnn.com](http://edition.cnn.com/)

We could only fix this one for v0.5.1. The other two issues do not appear to have a quick solution, so we will attempt to address them in v0.6.0.

**Comment by amovar18** [comment]
The scenario for the zero cookie issue has been addressed in PR 513.

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.5.1](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.1)
