### ISSUE TITLE
Cookies overview - blocked reason counts could deep link to pre-applied filters

### ISSUE THREAD

**Issue by rupesh1** [GoogleChromeLabs/ps-analysis-tool#588]
## Feature Request

**Description:**
1. Complete an analysis on a website with blocked cookies
2. Scroll down to Blocked Reasons
3. There should be a count of cookies associated to the blocked reason (e.g. 'ExcludeThirdPartyPhaseout')

Expected: Tapping the count should apply the filter to the domain level view and take you to the first domain where there is a blocked cookie (maybe prompt if there's already a filter applied that it will be unset)
Actual: The count is non-interactive

Cookies Overview page with non-interactive count
<img width="1512" alt="Fullscreen_09_04_2024__13_19" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/3313870/91857f89-e206-4714-bb74-3298493a9649">

Ideally tapping the count should take you to this screen with the filter applied
<img width="1512" alt="Fullscreen_09_04_2024__13_26" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/3313870/c93291d7-65f3-4e1e-b426-c22320b89e00">

**Comment by milindmore22** [comment]
Hello @rupesh1 

Great suggestion!, This feature is actually already on the roadmap. You can find related discussions in issue #505 and pull request #542. It's scheduled to be released in version 0.7.0

**Comment by rupesh1** [comment]
Great to hear, I'll close this one
