### ISSUE TITLE
Pop up displays no data on a tab revisit

### ISSUE THREAD

**Issue by ayushnirwal** [GoogleChromeLabs/ps-analysis-tool#60]
**Describe the bug**
The first time any site is checked the count and cookie listing appear fine, but after 2/3mins that site/tab is revisited the cookie listing is still there but the count on the extension disappears and on click of it asks to refresh the page.

**To Reproduce**
- Make sure the extension icon is pinned.
- Go to a website.
- Open the cookies tab in the privacy sandbox panel in the devtools.
- Open the pop up ( should work correctly till here ).
- Close the pop up and wait for 2-3 mns the cookie count over the extension icon would disappear.
- Open the pop up  

**Expected behavior**
- Pop count should not disappear.
- Pop up should show proper data rather than the message "Please refresh this page to view cookies"

**Screenshots**
![Screenshot 2023-07-14 at 11 31 11 AM](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/53055971/873f40de-7218-4f19-aa48-d6d07eeb8cdf)

**Additional context**
This bug, which only affects the pop-up, is known to occur very rarely and cannot be replicated by everyone.

**Comment by amedina** [comment]
@maitreyie-chavan Please provide an update.
