### ISSUE TITLE
Frame Overlays 

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#61]
## Feature Request

**Description:**
Visually present key information about frames on a given page. A semi-transparent overlay would be rendered on top of frames on the page, and within the overlay, key information about the frame is presented. 

**User Story:**
As a developer/user, I want understand the status and behaviors of embedded content on a given page and the corresponding cookies, so that I can easily assess the impact of blocked 3P cookies on the different parts of a site.

**Acceptance Criteria:**
- [ ] Frame identification
- [ ] Frame overlay rendering
- [ ] Display frame information (e.g. permission policies, cookies)

cc: @kevinkiklee, @sayedtaqui, @pradeep910

**Comment by amedina** [comment]
<img width="1627" alt="Screenshot 2023-07-14 at 1 33 23 PM" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/506089/48b26994-4a89-4589-be18-d3074ca9fb27">

**Comment by amedina** [comment]
To start off with a light feature set for the extension in the beginning, useful information to display in the overlay would be permissions policy.  A question often raised by partners is which third-party has access to what feature, and also how they can be controlled.  Right now, the users can examine the permissions policy of each frame by diving deep into the Applications of DevTools, but the information is not easy to parse.

<img width="1748" alt="Screenshot 2023-07-14 at 1 35 06 PM" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/506089/56eb5c53-dd96-4913-8698-618eb3f37601">

The above DevTools  screenshot is also taken from CNN, and you can see how many iframes are present on the page.  The developer will have to manually check each frame for auditing permissions.  Instead, a togglable frame overlay can provide important information to the user in a more manageable way.

**Comment by dmdabbs** [comment]
When I read your mention of "frame overlays," Prebid's "Professor Prebid" [extension](https://github.com/prebid/professor-prebid) came to mind. It provides nice xray vision to what's going on under the hood for a site using Prebid header bidding. Ops teams for sites permitting PAAPI nee FLEDGE auctions would want something to help them see/debug those GPS-enabled placements.
