### ISSUE TITLE
Unified demo site to exercise/demonstrate full capabilities of PSAT's extension and CLI

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#62]
## Feature Request

**Description:**
Build unified site with all scenarios and CUJs we use to demonstrate the value added by the tool in analyzing and deugging each of them. This is the central place to demonstrate the capabilities of the tool and educate users on how to leverage them.

**User Story:**
As a developer I want to understand easily the capabilities offered by PSAT's extension and CLI via their application to simplified demos and examples.

**Acceptance Criteria:**
- [x] Baseline demos for extensive set of CUJs (Analytics, e-commerce, embedded content, etc). 
- [x] Demo site is easy to use and understand
- [x] Demo site is leverage in tool guidance on how to use and analyze the examples using the PSAT (this tool)

**Comment by amedina** [comment]
Demos will use a set of domains registered for them specifically (e.g. domain-aaa.com, domain-bbb.com, domain-ccc.com). Some samples demonstrate aspects that require HTTPS. Need to determine how to allow for that on domains mapped to localhost.  cc @gagan0123

**Comment by actual-saurabh** [comment]
This is a subset of #207 in a way. The approach to that would decide the approach on this.

**Comment by maitreyie-chavan** [comment]
Closing this issue for now, further enhancements to be made for the current demo sites will be tracked individually.
