### ISSUE TITLE
Add "Clear all" option to filter settings

### ISSUE THREAD

**Issue by maitreyie-chavan** [GoogleChromeLabs/ps-analysis-tool#621]
## Feature Request

**Description:**
Add "Clear all" option to filter settings when **one** or more filter options have been selected. 

**Motivation:**
The "x" option to remove filters serves the use case where the user wants to eliminate a single option from a list of filter options, while the "Clear all" option can be used to clear one or more filter options selected in a single click.

**Comment by gagan0123** [comment]
Released in [version 0.8.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.8.0)
