### ISSUE TITLE
Broken Download Button UI in DevTools Cookie Frame After Visiting Landing Page Subpages.

### ISSUE THREAD

**Issue by milindmore22** [GoogleChromeLabs/ps-analysis-tool#624]
**Describe the bug**

The Download button in the DevTools panel is experiencing a UI malfunction after visiting sub-pages of landing pages. This bug manifests as a broken UI for the button.

**To Reproduce**

1. Navigate to any website.
2. Open the DevTools panel and locate the cookie frame.
3. Verify that the Download button is displayed correctly.
4. Visit another landing page and explore its sub-pages (e.g., Private Advertising, Tracking Protection).
5. Return to the cookie frame within DevTools.
6. Observe the broken UI affecting the Download button.

**Expected behavior**
The Download button should maintain its consistent visual appearance throughout all DevTools interactions, regardless of the previously visited website pages.

**Screenshots**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/1132541/01e49f9b-d59e-40d0-9c80-8ac71703927e

**Desktop (please complete the following information):**

**Open Tabs:** 1
**Active Extensions:**
Privacy Sandbox Analysis Tool: ehbnpceebmgpanbbfckhoefhdibijkef
Google Docs Offline: ghbmnnjooekpmoecnnnilnnbdlolhkhi
**Chrome Version:** Version 123.0.0.0 (x86-64)
**PSAT Version:** 0.7.0
**OS - System Architecture:** MacOS (x86-64)

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.8](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.8.0)
