### ISSUE TITLE
Improve the UI/UX for "Known Breakages" section

### ISSUE THREAD

**Issue by maitreyie-chavan** [GoogleChromeLabs/ps-analysis-tool#642]
## Feature Request

**Description:**
We need to improve the information displayed under the Known Breakages section by achieving the following - 

- [x] Remove the box UI when an accordion item is expanded
- [x] Remove the separator line after the last item
- [x] Remove the bullets/feature list mentioned under GIS & GSI
- [x] Remove the full-stops after each detection title
- [x] Shorten the detection title text and make it standardized 
- [x] Make the CTA under each detection more informative - Example: To inquire further about the same, please visit the support forum

**Comment by gagan0123** [comment]
Released in [version 0.8.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.8.0)
