### ISSUE TITLE
Update timeline image under Facilitated Testing page

### ISSUE THREAD

**Issue by maitreyie-chavan** [GoogleChromeLabs/ps-analysis-tool#651]
## Feature Request

**Description:**
Further to the information shared in [this post](https://privacysandbox.com/news/update-on-the-plan-for-phase-out-of-third-party-cookies-on-chrome/), we need to update the timeline image shown under the Facilitated Testing page to the following one

<img width="708" alt="Screenshot 2024-04-29 at 7 53 49 PM" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/20221326/5114db50-5d06-4bd0-80c1-036b9b810575">

**Comment by gagan0123** [comment]
Released in [version 0.8.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.8.0)
