### ISSUE TITLE
Design Landing Page for Cookies menu element in Privacy Sandbox Panel

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#66]
## Feature Request

**Description:**

**Motivation:**
As a user I want to have access to a landing page of the Cookies main area for Privacy Analysis DevTools panel,  with overall information, aggregated stats,  general insights, and entry points to information/educational resources. 

**Acceptance Criteria:**
- [x] Information currently included in the extension popup should be moved here (https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/5)
- [x] Number of cookies with issues
- [x] Number of frames in page and number of frames with associated cookies
- [ ] Link to "Preparing for 3PCD" Landing page 

**Additional Information:**
Design

<img width="1347" alt="image" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/6297436/41b307ec-2a75-4037-aa9d-8c489845048a">

<img width="1113" alt="image" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/6297436/1d8b1fc7-82ab-4548-a315-a887c65b7cdf">

**Comment by sayedtaqui** [comment]
Would need the link for adding
> Link to "Preparing for 3PCD" Landing page
