### ISSUE TITLE
CLI: Inconsistent Highlighting for Blocked Cookies in Cookie Issues section

### ISSUE THREAD

**Issue by gagan0123** [GoogleChromeLabs/ps-analysis-tool#680]
**Describe the bug**
While using the PSAT CLI version 0.8.0 for analyzing livemint.com, the yellow highlight for certain cookies does not appear for a few cookies in the "Cookie Issues" table.

**To Reproduce**
1. Analyze the site using CLI with the command: 
  `npm run cli -- -u https://livemint.com`
3. Open the CLI output URL.
4. Navigate to 'Cookie Issues'.
5. Observe the display of cookies where the expected yellow background is missing for some entries.

**Expected behavior**
All cookies that are blocked are supposed to be highlighted with a yellow background.

**Screenshots**
![psat-0 8 0-cli-highlight-issue](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/1535505/f96acea6-96f3-465c-8f80-180c227c5c27)

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS x86_64
 - Node: v18.17.1
 - PSAT CLI: 0.8.0

**Comment by maitreyie-chavan** [comment]
Released in [v0.9](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.9.0)
