### ISSUE TITLE
Intermittent Library Detection Error in "Known Breakages" section

### ISSUE THREAD

**Issue by gagan0123** [GoogleChromeLabs/ps-analysis-tool#681]
**Describe the bug**  
During sequential navigation of web pages in Google Chrome, the PSAT panel within Chrome DevTools intermittently displays the following error message under the "Known Breakages" section  

 `A library detection error occurred. Please reopen DevTools on a valid URL.`  

**To Reproduce**
1. Launch Google Chrome and sequentially open various web pages.
2. Activate Chrome DevTools.
3. Navigate to the 'Application' tab and select the 'Cookies' section under the psat panel.
4. Observe the occurrence of the error message in the "Known Breakages" section.

**Expected behavior**
The expected behavior is that the cookies section under the PSAT panel should consistently display accurate cookie information without triggering error messages, regardless of the number of pages accessed or their order.

**Screencast**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/1535505/5a44872d-ed39-4020-a3a0-d129c6be291e

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS x86_64
 - Browser: Google Chrome
 - Version: 124.0.6367.118 (Official Build) (64-bit)
 - PSAT Version: 0.8.0

**Additional context**
It does not replicate consistently.

**Comment by pavanpatil1** [comment]
Not able to replicate this, It has been addressed in the v.0.9 release. Therefore, closing this issue. 


[known.webm](https://github.com/user-attachments/assets/2cb8e513-91c7-4cf7-b044-4dac54517e3f)
