### ISSUE TITLE
Exemption section disappearing

### ISSUE THREAD

**Issue by fellyph** [GoogleChromeLabs/ps-analysis-tool#682]
**Describe the bug**
Analyzing nytimes.com, the exemption section inside the cookies insight page lists eight cookies and disappears after a while. 

**To Reproduce**
1. Go to `nytimes.com`
2. Open the cookies insight page when the page is loading
3. Search for the Exemption section
4. Wait for the load completely 
5. the section disappears after a few seconds 

**Expected behavior**
The section should not disappear after the page loads

**Screenshots**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/330792/4856de83-527c-4bd0-bb8c-afde0e7103b1

<img width="2507" alt="Screenshot 2024-05-17 at 16 29 03" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/330792/bd9fafb3-18e2-478a-95ef-2dbfe528f81d">

**Desktop (please complete the following information):**
 - OS: macOS 14.5
 - Browser Chrome 125.0.6422.61 (Official Build) (arm64)
 - Version 0.8.0

**Comment by maitreyie-chavan** [comment]
Released in [v0.9](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.9.0)
