### ISSUE TITLE
Add the website url as a prefix to the downloaded report

### ISSUE THREAD

**Issue by fellyph** [GoogleChromeLabs/ps-analysis-tool#688]
## Feature Request

**Description:**
When the user saves the cookie data from the cookie table, it creates a CSV file named `Cookie Report.csv`. This feature adds a prefix with the URL from the audit website. For example, the download HTML functionality includes `www-example-com-report.html`; to be consistent, it should download a CSV file with the same structure, `www-example-com-report.csv`.

**Motivation:**
When the user saves several files from different domains, it is hard to identify them and the download feature should be consistent across the extension. 

**User Story:**
As a user, I want to have the report with the website url so that I can easily identify the reports.

**Acceptance Criteria:**
- [ ] download a report from the cookie table with the website URL as a prefix

**Additional Information:**
<img width="328" alt="Screenshot 2024-05-23 at 15 37 11" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/330792/d68f4b7b-3201-4a36-a7ac-67b757a8d200">

**Comment by maitreyie-chavan** [comment]
Released in [v0.9](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.9.0)
