### ISSUE TITLE
Filter losing the state when the user refreshes the page

### ISSUE THREAD

**Issue by fellyph** [GoogleChromeLabs/ps-analysis-tool#690]
**Describe the bug**
Analyzing data at the cookie table with filters selected, I noticed the filters lose their state when the user reloads the page, not all filters are maintained after the user reloads the page manually.

**To Reproduce**
1. Audit a website
2. Open the cookie table at Devtools
3. Select the filter third-party and cookies categories "Uncategorized." 
4. Reload the page and observe the selected filters

**Expected behavior**
The Filters should keep the state, and all filters should be selected when the user reloads the page.

**Screenshots**
https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/330792/0e88b00c-9196-4000-b28f-befe7929590d

**Desktop (please complete the following information):**
 - OS: MacOS 14.5
 - Browser Chrome Version 125.0.6422.77 (Official Build) (arm64)
 - Version v0.8.0

**Comment by fellyph** [comment]
@maitreyie-chavan, we can close this issue the problem was fixed:

https://github.com/user-attachments/assets/26618714-88a2-4966-ad5a-0a11e0712854

**Comment by maitreyie-chavan** [comment]
Addressed and released as a part of [v0.9](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.9.0)
