### ISSUE TITLE
Cookies landing page navigation losing reference

### ISSUE THREAD

**Issue by fellyph** [GoogleChromeLabs/ps-analysis-tool#697]
**Describe the bug**
At the cookies landing page, when the user selects the "Blocked Cookies" section in the main navigation, the page is reloaded. The selection jumps to "Known Breakages".  The reference to the menu should be kept in the previous selection.

**To Reproduce**
1. Go to `bbc.com` and inspect the page
2. Open the cookies landing page at the Privacy Sandbox tab
3. Select Blocked cookies at the main navigation on the top right
4. Reload the page
5. Observe the menu selection
6. The selection changes to "Known Breakages"

 

**Expected behavior**
The selection should be preserved when the user reloads the page.

**Screenshots**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/330792/8bb1fe6e-366e-4fc0-9e0f-e85b790f5233

**Desktop (please complete the following information):**
 - OS: MacOS 14.5
 - Browser Chrome Version 125.0.6422.113 (Official Build) (arm64)
 - Version v0.8.0

**Additional context**

**Comment by maitreyie-chavan** [comment]
Released in [v0.9](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.9.0)
