### ISSUE TITLE
Disable the download CSV button for zero cookies

### ISSUE THREAD

**Issue by fellyph** [GoogleChromeLabs/ps-analysis-tool#724]
**Describe the bug**

In the Cookie Table view, when no cookies are listed in the table, the "Download CSV" button should not be active. Currently, the button remains enabled and clickable even when the table is empty. This behavior can mislead users into believing they can download a CSV file when no data is available.

**To Reproduce**
1. Go to the cookie table with an empty listing 
2. Click on the download CSV button close to the search bar
4. Nothing will happen

**Expected behavior**
When the Cookie Table is empty, the "Download CSV" button should be disabled or visually indicated as unavailable to prevent user confusion.

**Screenshots**
![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/330792/ebe979c9-9bc1-400e-882b-941e8fd4117f)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome 126
 - Version PSAT 0.8

**Additional context**
bug reported by @milindmore22

**Comment by maitreyie-chavan** [comment]
@fellyph Please reconfirm if this has been fixed so that we can close this issue out
