### ISSUE TITLE
Make cookies table preferences persistent

### ISSUE THREAD

**Issue by mohdsayed** [GoogleChromeLabs/ps-analysis-tool#74]
## Feature Request

**Description:**
All cookie table preferences like sorting, column filtering, selected filters, etc should be persistent for a given tab.

**User Story:**
As a user, I want to keep my preferences persistent in the cookies tab of the “Privacy Sandbox” panel. This will also help me for debugging purposes.

**Acceptance Criteria:**
Following preferences should be persistent
- [x] Column sorting
- [x] Column Resizing
- [x] Selected Columns from the available list.
- [x] Selected filters and chips
- [x] Selected frame.

**Comment by amedina** [comment]
There are still cases when users switch between different frames when analyzing the cookies for a given site and the settings change. Some times the filter selections are cleared, and some times the filter options are collapsed.

The expected UX is that the filter selections should remain the same when the user is analyzing a given tab, and the filter options should remain open as the user switches between frames. 

cc/ @mohdsayed @amovar18 @maitreyie-chavan

**Comment by amedina** [comment]
Also observing filters set on a frame being maintained for that frame was reset for other frames.

**Comment by amedina** [comment]
Further testing shows inconsistent behavior and settings not maintained as users switch between frames in the cookies table for a single page. 

Examples to reproduce: https://toyota.jp.

**Comment by maitreyie-chavan** [comment]
> https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/74#issuecomment-1798014829

The new issues findings are being addressed via https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/206

Closing this ticket in favor of the #206
