### ISSUE TITLE
Inline scripts and data for the CLI analysis report file

### ISSUE THREAD

**Issue by mohdsayed** [GoogleChromeLabs/ps-analysis-tool#744]
## Feature Request

**Description:**
CLI analysis generates three files: index.html, index.js, and out.json where the index.js file is enqueued in index.html. Sharing a single index.html file would be easier if we inline the script and data.

**Comment by maitreyie-chavan** [comment]
Released as a part of [v0.10](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.10.0)
