### ISSUE TITLE
Extension: Feature separation and Feature navigation widget for each PSAT sections

### ISSUE THREAD

**Issue by maitreyie-chavan** [GoogleChromeLabs/ps-analysis-tool#780]
## Feature Request

**Description:**
Provide access to PSAT features for each Privacy Sandbox area (Related Website Sets, Protected Audience, etc.) via clearly separated sections and provide navigation widget in each PS area section

**Comment by gagan0123** [comment]
Released as a part of [v0.11.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.11.0)
