### ISSUE TITLE
Error trying to parse csv input with PSAT CLI v0.10

### ISSUE THREAD

**Issue by Dbrown910** [GoogleChromeLabs/ps-analysis-tool#794]
**Describe the bug**
Sitemap and URL input on the command line produce a PSAT report, but passing in a csv file results in an error

**To Reproduce**
1. Download and install PSAT CLI v0.10
2. Run npm run cli -- -c ./path/to/any/csv
3. See the error: "Error: ./path/to/csv is not valid numeric value."

**Expected behavior**
Aggregated PSAT report is generated 

**Screenshots**
In this screenshot I show the csv file does exist in my directory structure using the ls command. I also gave the CLI a numeric value just to see what happens, but then I get an error that path must be a string (expectedly). I also run a basic URL and the sitemap URL just to show the other inputs are good

![Screenshot 2024-07-31 at 6 25 42 PM](https://github.com/user-attachments/assets/0c3ec22a-10a4-4ab0-979b-8b89e9063d4e)
d

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.5
 - Browser : Chrome 
 - Version : 127

**Additional context**

**Comment by milindmore22** [comment]
Hello @Dbrown910

Thank you for doing a thorough test and reporting back to us with the issues you encountered. As we checked your description and screenshot, we found that you are using old CLI options. `-c`

The version [0.10.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.10.0) introduced some changes to the CLI options. The `-c` option is now replaced by the `-f` option.

With the -f option, you can specify the file path to CSV or sitemap. E.g., `npm run cli -- -f /path/to/any.csv` or `npm run cli -- -f /path/to/any.xml`

Please consider using `-h` or `--help` to learn about new options while running PSAT CLI, or please check our [updated wiki](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/PSAT-Command-Line-Interface#cli-options) page.

**Comment by Dbrown910** [comment]
Ahh okay! Thanks for clarifying @milindmore22 !
