### ISSUE TITLE
Add `Wiki` section

### ISSUE THREAD

**Issue by maitreyie-chavan** [GoogleChromeLabs/ps-analysis-tool#820]
Integrate the project's Wiki within the Privacy Sandbox Analysis tool's feature areas, enabling users to view, search, and navigate through the project documentation without leaving the tool. 

The Wiki embed should provide the same user experience to users as when they access it directly in the Github repository.

Users can access the embedded Wiki from a  "Documentation" or "Help" section in the sidebar.

Reference: https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki

**Comment by gagan0123** [comment]
Released as a part of [v0.11.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.11.0)
