### ISSUE TITLE
Update order of PAT Section components

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#824]
The order of the components in the Private Advertising section should be as follows:

1. Topics
2. Protected Audience
3. Attribution Reporting
4. Private Aggregation

**Comment by 050898056** [comment]
Direct login to recover my account  b7il2222@gmail.com

**Comment by 050898056** [comment]
> Direct login to recover my account  b7il2222@gmail.com

**Comment by gagan0123** [comment]
Released as a part of [v0.11.0](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.11.0)
