### ISSUE TITLE
Update outdated URLs in Wiki

### ISSUE THREAD

**Issue by gagan0123** [GoogleChromeLabs/ps-analysis-tool#829]
**Describe the bug**
Multiple links in the PSAT wiki point to outdated `privacysandbox.info` URLs. The Privacy Sandbox documentation has been moved to `developers.google.com/privacy-sandbox/`.

**To Reproduce**
1. Go to any of the following pages on the PSAT wiki: 
1.1. https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/Tracking-Protection
1.2. https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/Private-Advertising
3. Look for links that end in `privacysandbox.info`.
4. Click on the link.
5. You may be taken to an outdated or broken page.

**Expected behavior**
All links should point to the up-to-date documentation on `developers.google.com/privacy-sandbox/`.

**Screenshots**
![image](https://github.com/user-attachments/assets/15965d6e-0c44-4951-95ea-8d9a44a4a634)

**Desktop (please complete the following information):**
Not Applicable

**Additional context**
This issue is to ensure that the PSAT wiki provides accurate and up-to-date information. Please update all links to the correct Privacy Sandbox documentation.

**Comment by fellyph** [comment]
Hi @gagan0123 

I want to double-check the new URLs, but I couldn't find alternatives for two items marked with (?).

**Tracking Protection**
Proposals - (?)
User-agent reduction - https://developers.google.com/privacy-sandbox/protections/user-agent
User-Agent reduction snippets - (?)
IP Protection - https://developers.google.com/privacy-sandbox/protections/ip-protection
Privacy Budget - https://developers.google.com/privacy-sandbox/protections/privacy-budget
Bounce Tracking mitigation - https://developers.google.com/privacy-sandbox/protections/bounce-tracking-mitigations

**Private Advertising** 

Private Aggregation - https://developers.google.com/privacy-sandbox/private-advertising/private-aggregation

**Comment by gagan0123** [comment]
Yes @fellyph 

You can remove that part, as Chrome's stable version is already shipping with User-agent reduction, testing the same using snippets is not needed anymore.

**Comment by gagan0123** [comment]
Closing this issue as the updates have been merged to the wiki.
