### ISSUE TITLE
Partitioned Cookies - Incorrect "Cookie Set" status

### ISSUE THREAD

**Issue by gagan0123** [GoogleChromeLabs/ps-analysis-tool#85]
**Describe the bug**
The "Cookie Set" status of all partitioned cookies always set as "No" even though partitioned cookies are set.

**To Reproduce**
1. Open any page that sets partitioned cookies.
2. Open the Privacy Sandbox in Developer Tools.
3. Observe the "Cookie Set" ~~and the "IBC Compliant"~~ status of any partitioned cookie in the site.

**Expected behavior**
The extension should show correct "Cookie Set" ~~and "IBC Compliant"~~ status for partitioned cookies.

**Screencast**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/1535505/00e0fc19-88fb-4afc-9d1e-0d2be4f2b28c

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS
 - Browser: Google Chrome
 - Version: 114.0.5735.198 (Official Build) (64-bit)

**Comment by amedina** [comment]
Related to #156.

**Comment by gagan0123** [comment]
Irrelevant now so closing it as cookie set has been replaced with yellow highlight and its taking care of the partitioned cookies as well.
