### ISSUE TITLE
Reporting breakage and feedback

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#9]
## Feature Request

**Description:**
Capability for submitting breakage reports directly to Google. 

**User Story:**
As a developer/web-user observing and analyzing PS/3PCD debugging scenarios I want to be able to report breakages to the right feedback channels.

**Acceptance Criteria:**
- [ ] Report form aligns with Bug Report Template 
- [ ] Configurable endpoints (e.g. Buganizer, Github)

**Comment by maitreyie-chavan** [comment]
We have added an [issue template](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/new?assignees=&labels=&projects=&template=third-party-cookie-breakage-report.md&title=) to help users report a breakage, closing this task for now.
