### ISSUE TITLE
Capture Salesforce Cookies in DB/classifier

### ISSUE THREAD

**Issue by amedina** [GoogleChromeLabs/ps-analysis-tool#90]
**Description:**
The Salesforce Platform uses cookies to improve functionality and accelerate processing times.  The goal of this task is to ensure that all these cookies are part of the cookie DB used for cookie classification.

**Additional Information:**
* [Salesforce Platform Cookies](https://help.salesforce.com/s/articleView?id=sf.platform_cookies.htm&type=5)

**Comment by jkwakman** [comment]
Salesforce platform cookies have been checked and added to the [Open Cookie Database](https://github.com/jkwakman/Open-Cookie-Database/blob/master/open-cookie-database.csv). If you want to add any more cookies / platforms please let me know.

**Comment by jkwakman** [comment]
Dear @pradeep910,

There was a small change in the cookie database:
https://github.com/jkwakman/Open-Cookie-Database/pull/21

Latest version removes the following identifiers from the file:

N/A
None
Advertiser's website domain
Website domain

Empty cell's are shown if data is not available or a cookie has been placed on a first party domain. V0.1 still has the old setup but is deprecated from now on. This change may have an effect on the PS Analysis tool, so I thought it would be useful to let you know.

If you have any more questions or feedback please let me know.

Kind regards,

Jack Kwakman

**Comment by amedina** [comment]
Thank you @jkwakman!
